### ISSUE TITLE
Outdated variable documentation for 'doom-cleanup-processes-alist'

### ISSUE THREAD

**Issue by UndeadKernel** [hlissner/.emacs.d#10]
Hey there,
I believe the docstring for the variable 'doom-cleanup-processes-alist' ([defined in core.el](https://github.com/hlissner/.emacs.d/blame/master/core/core.el#L52)) is outdated. The docstring mentions the function 'doom:cleanup-processes' which I believe doesn't exist anymore. Instead, you use the variable in the function 'doom/kill-process-buffers' inside of defuns-buffer.el ([which is found here](https://github.com/hlissner/.emacs.d/blob/master/core/defuns/defuns-buffers.el#L143))

**Comment by hlissner** [comment]
Ah, good catch! I've updated it.

**Comment by UndeadKernel** [comment]
Would you like to continue receiving these types of small issues and pull requests?
From reviewing your code, I have found some more small things such as this last one that I would gladly fix/point-out.
:D

**Comment by hlissner** [comment]
Oh yes, please do! I've only recently begun refactoring. A lot has changed in the past year, and when I first started this I knew zilch about elisp, so I don't doubt there are problems peppered throughout. I'd appreciate any help!
