### ISSUE TITLE
lexical binding refactor

### ISSUE THREAD

**Issue by aliem** [hlissner/.emacs.d#100]
Hello,
I have just a quick note. After the last major refactoring in c7254e7 there are a couple of Symbol is void errors.

My elisp is weak and still needs training and discipline. I could see `+ivy--get-buffer-attrs` in https://github.com/hlissner/.emacs.d/blob/master/modules/completion/ivy/autoload/ivy.el#L16 is referencing `min-name` and `min-mode` defined in `+ivy--get-buffers`.

If I can fix anything, I'll gladly send you a pull request.

**Comment by hlissner** [comment]
Good catch! I just pushed a fix for it. Thank you for reporting it!
