### ISSUE TITLE
Symbol’s value as variable is void: wend

### ISSUE THREAD

**Issue by Luladjiev** [hlissner/.emacs.d#101]
When I search with :ag and I hit return on one of the occurrences I get this error:
`nlinum-hl-flush-window: Symbol’s value as variable is void: wend`

**Comment by hlissner** [comment]
Sorry, this is a problem with `nlinum-hl`, I've fixed it upstream in https://github.com/hlissner/emacs-nlinum-hl/commit/294037f5231375ac63836637651585f8b82b962d

**Comment by hlissner** [comment]
Forgot to mention: while we wait for Melpa to pull the update you can fix this with `(remove-hook 'nlinum-mode-hook #'nlinum-hl-mode)`

**Comment by Luladjiev** [comment]
Thanks

**Comment by hlissner** [comment]
With #59 almost resolved, I've removed `nlinum-hl` entirely in https://github.com/hlissner/.emacs.d/commit/7ba22d0d8676907d83db9f6b7f5575583309ff0e. If you update, this problem should be gone either way.
