### ISSUE TITLE
Proposal for app/irc

### ISSUE THREAD

**Issue by bandresen** [hlissner/.emacs.d#103]
https://github.com/bandresen/.emacs.d/tree/master/modules/app/irc

I've also set up some faces.
https://github.com/bandresen/emacs-doom-themes/

Screenshot of how it generally looks is here:
http://i.imgur.com/BCZEyW4.png

Looking forward to your thoughts!

**Comment by hlissner** [comment]
That looks fantastic. Precisely the stack I was considering and it looks great! A few thoughts and questions:

1. `doom-theme`: Could you use `highlight` instead of `blue`? This is slightly more flexible; `doom-one` and `doom-vibrant` both use blue for highlight.

2. Why do you defer your `+irc-disconnect-hook` and `circe-server-connected-hook` hooks for 5 minutes? To overcome notification-overload during buffer playback, or is there another reason?

3. Unrelated, but I'm also a `pass` user. If it isn't too much trouble, I'd be interested in `tools/password-store` as well!

**Comment by bandresen** [comment]
1. Done.

2. Precisely. I use ZNC and that caused my naive alert system to freak out if I haven't been connected in awhile. I actually haven't tried it the normal way in a while I just ported my old stuff to doom and updated it with the style guide.
I saw `circe-notifications` has anti-spam now so maybe this isn't needed.
The visual aesthetic with the padding and such is very recent for me, so it isn't done yet. I don't want to use an advise that changes the actual nick. I would like to realize this with faces instead but have never done faces. In addition you can get collisions if you cut things off so having a fallback should probably be added just in case. 

3. It's on master on my end, but it isn't done yet either. Previously I had three things: =password-store= library for the fundamentals (which works), `pass` which is a more graphical manager (doesn't work yet in doom due to shackle) and auth-password-store (doesn't work yet) which makes it work via the `auth-source` backend.
A goal for the future is ivy integration with this.

**Comment by hlissner** [comment]
1. Great! I'll accept the PR as soon as I receive it.

2. I'd like to try my hand at a solution with faces. Go ahead and file that PR and I'll have a go at it.

3. I'd accept the PR anyway. It's rare that I have problems resolving shackle issues (I've gotten so used to fixing them!), and I think I can adapt an ivy solution from helm-pass.

**Comment by hlissner** [comment]
Alright, I've added ivy integration and shackle issues resolved to `tools/password-store`. Give it a test if you get a chance and let me know if there's anything you think is missing.

**Comment by hlissner** [comment]
I'm about done with `app/irc`, but i have a question:

  ```emacs-lisp
  (add-hook! '+irc-disconnect-hook
    (run-at-time "5 minute" nil #'circe-reconnect-all))
  ```

Could you explain what this is for? Does circe have connection issues? Or is this a ZNC thing?

---

Besides that:

+ Among other things, I'm now using `compose-region` to truncate nicks non-destructively.
+ I've removed the 5-minute deferral of `enable-circe-notifications` and replaced it with a `+ivy-defer-notifications` option (number of seconds to wait before notifications are enabled). You'll want that set to 300 to get that functionality back.

**Comment by bandresen** [comment]
Oh that's an artifact from my personal setup. Circe has auto-reconnect built-in but I have `autossh` running to connect to the znc  host and that's not as quick to realize the connection was dropped as circe.

I'm still getting used to what to put where when adding functionality not already present in doom.

The nick thing sounds real nice! I'll check it out at a later time.
(I'm still coming to terms with how to rebase when you PR'd stuff yourself into a repo and also personalized things. I'm more used to the rebase + patch model instead of trying to align branches.)

**Comment by hlissner** [comment]
> I'm still getting used to what to put where when adding functionality not already present in doom.

Perhaps this post https://github.com/hlissner/.emacs.d/issues/88#issuecomment-306222820 can help?

> ... with how to rebase when you PR'd stuff yourself into a repo ...

I sympathize. You're not that many commits deep though. If you'd like pulling from upstream to stay easy, I'd suggest:

1. Create a `rescue-me` branch (for example)
2. Revert master to upstream/master
3. Cherry-pick your customizations from `rescue-me`
4. Move all your customization into `modules/private` to prevent upstream conflicts (like with `evil-magit` and `mu4e-send-delay`). 

   https://github.com/hlissner/.emacs.d/issues/88#issuecomment-306222820 (same link as above) offers a few tricks for that.

```bash
# assuming you're in master
git remote add -f upstream https://github.com/hlissner/.emacs.d
git branch rescue-me
git reset --hard upstream/master
# use `git log --oneline --graph rescue-me` to find those SHA's
git cherry-pick <SHA...>
```

I hope all that can be of some use, and sorry if none of that is new to you.

---

On a separate note, we've completed the objective of this issue. Thanks for your help! Feel free to email me (henrik@lissner.net) if you'd like to follow up on anything unrelated to `app/irc` or `tools/password-store`.
