### ISSUE TITLE
stripe-buffer-mode doesn't work

### ISSUE THREAD

**Issue by bandresen** [hlissner/.emacs.d#105]
On the first invocation it errors. Every other time it silently fails. (No stripes.)
Here is the backtrace.

``
Debugger entered--Lisp error: (wrong-type-argument stringp ("#23272e" "#262626" "brightblack"))
  internal-set-lisp-face-attribute(stripe-highlight :background ("#23272e" "#262626" "brightblack") #<frame DOOM Emacs 0x11e3c30>)
  set-face-attribute(stripe-highlight #<frame DOOM Emacs 0x11e3c30> :background ("#23272e" "#262626" "brightblack"))
  apply(set-face-attribute stripe-highlight #<frame DOOM Emacs 0x11e3c30> (:background ("#23272e" "#262626" "brightblack")))
  face-spec-set-2(stripe-highlight #<frame DOOM Emacs 0x11e3c30> (:background ("#23272e" "#262626" "brightblack")))
  face-spec-recalc(stripe-highlight #<frame DOOM Emacs 0x11e3c30>)
  face-spec-set(stripe-highlight ((((class color) (background dark)) (:background "#444444")) (((class color) (background light)) (:background "#CCCCCC"))) face-defface-spec)
  custom-declare-face(stripe-highlight ((((class color) (background dark)) (:background "#444444")) (((class color) (background light)) (:background "#CCCCCC"))) "Face for stripes." :group stripe-buffer)
  byte-code("\300\301!\210\302\303\304\305\306\307%\210\310\311\312\313\306\303%\210\310\314\315\316\317\320\321\"\321\317\320\316\"\257C\322\306\303%\210\323\324\325\326\306\303\327\330&\210\323\331\332\333\306\303\327\334&\207" [require cl-lib custom-declare-group stripe-buffer nil "Use different background for even and odd lines." :group wp custom-declare-face stripe-highlight ((((class color) (background dark)) (:background "#444444")) (((class color) (background light)) (:background "#CCCCCC"))) "Face for stripes." stripe-hl-line t :background face-attribute default :foreground "Bold face for highlighting the current line in Hl-Line mode." custom-declare-variable stripe-height 1 "Height of stripes." :type integer stripe-in-table-regex "^[ 	]*\\(?1:[|+].+[|+]\\) *$" "Regular expression that determines whether a line contains a table row.\nUsed by `stripe-table-mode' Only the first matching group will be painted." string] 9)
  autoload-do-load((autoload "stripe-buffer" nil t nil) stripe-buffer-mode)
  command-execute(stripe-buffer-mode record)
  #[257 "\304\305!\203\f
``

[Here it's in link form as it looks bad via the issue](https://paste.in-ulm.de/?0b405a3b304784f9#qgigvmpIsk4piHMs89jPR/vqPhlaM5fAw8Z3yIAJlTg=)

My emacs-version:
`GNU Emacs 25.2.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.22.10) of 2017-04-22`

**Comment by hlissner** [comment]
Whoops, this is due to some vestigial code in [emacs-doom-theme](https://github.com/hlissner/emacs-doom-themes). It's fixed as of https://github.com/hlissner/emacs-doom-themes/commit/4b6482765e3be2c51a9d8d23bbbfb9a0c80bf4ac, and should resolve this issue.
