### ISSUE TITLE
Format specifier doesn’t match argument type

### ISSUE THREAD

**Issue by Luladjiev** [hlissner/.emacs.d#106]
With the latest commits when I start emacs I got this error in Messages
`Format specifier doesn’t match argument type`
and I can't do anything. It seems that your bindings / commands are not loaded as well (probably because of this error)
The error is in this line: https://github.com/hlissner/.emacs.d/blob/master/modules/ui/doom-dashboard/config.el#L152

I tried to debug it and I saw that doom-init-time is nil, the problem is that this hook does not trigger https://github.com/hlissner/.emacs.d/blob/master/core/core-packages.el#L308 or at least I think it doesn't, my elisp skills are still new so...

I've set doom-init-time to be 1 by default, not nil so I can check if the error still exists but it doesn't, the strange thing was that your SPC (leader) bindings still didn't work.

**Comment by Luladjiev** [comment]
So after bisecting the commits I've managed to find the problem package, it's password-store, when I comment it in init.el it works.

**Comment by hlissner** [comment]
I'm pushed a potential fix for this. Let me know if it resolves the issues or not.

**Comment by aminb** [comment]
I just tried, the error seems to still be present.

**Comment by Luladjiev** [comment]
As @aminb said still not resolved

**Comment by hlissner** [comment]
Odd. I've been unable to reproduce this. If the issue is password-store, could see if these produce an error (using `M-x eval-expression`):

```emacs-lisp
(require 'auth-password-store)
(auth-pass-enable)
```

They're the only things that run on startup in that module.

**Comment by Luladjiev** [comment]
Haven't tried your suggestion but I think this is the problem

`Warning (initialization): An error occurred while loading ‘c:/Users/lulad/.emacs.d/init.elc’:

File error: Cannot open load file, No such file or directory, auth-password-store`

**Comment by Luladjiev** [comment]
Same when evaluating your code
``
eval-buffer: Cannot open load file: No such file or directory, auth-password-store
``

**Comment by tjikini** [comment]
(package! auth-password-store) are needed when Emacs <26

**Comment by Luladjiev** [comment]
It does have a cond for it though https://github.com/hlissner/.emacs.d/blob/master/modules/tools/password-store/config.el#L32

**Comment by hlissner** [comment]
Ack, @tjikini you are correct. I had assumed `auth-password-store` was built into either `pass` or `password-store`.

@Luladjiev That cond is just an Emacs version check, because `auth-password-store` functionality is built into Emacs 26+.

In either case, as of https://github.com/hlissner/.emacs.d/commit/146de3e6186976c9b53c54e99a6144191891ba21 this should be fixed. Please let me know if that isn't the case.

**Comment by Luladjiev** [comment]
Yes that fixed the problem. Thanks!
