### ISSUE TITLE
Atom like whitespaces, tabs, newlines, vertical line

### ISSUE THREAD

**Issue by UtamaruMonster** [hlissner/.emacs.d#109]
Good day.

I'm quite new to emacs. Moving from Atom. To TERMINAL version of emacs.
Your Emacs configuration is like a god sent for a newcomer, thank you so much.

What i'm missing is this.
<img width="612" alt="screen shot 2017-06-15 at 10 13 20" src="https://user-images.githubusercontent.com/7836122/27172738-88978410-51b6-11e7-8783-5d9a108baad4.png">

Each space-mark as a **DOT**, newline-mark as something like **BOX DRAWINGS LIGHT DOWN AND LEFT**. Between each 2 spaces **VERTICAL LINE**.

I did this in **core-editor.el**
`tab-width 2
  whitespace-display-mappings
 '((tab-mark ?\t [?› ?\t]) (newline-mark 10 [9488 10]) (space-mark 32 [183] [46]))`

`(defun whitespace-mode ()
  (set-face-attribute 'whitespace-newline nil :background nil :foreground "gray30")
  (set-face-attribute 'whitespace-space nil :background "#232323" :foreground "gray30"))`

Any better way to write this?

This is what i get in emacs when i enable **global-whitespace-mode** with above configuration

<img width="231" alt="screen shot 2017-06-15 at 10 43 31" src="https://user-images.githubusercontent.com/7836122/27173021-9297e256-51b7-11e7-95d3-6f20ea6da766.png">

The most annoying part is the **DOT** in line numbers

Thank you for the help.

P.S. could you please add a **question label**

**Comment by hlissner** [comment]
There are three parts to this answer:

> 1. Why the dots are white

You are missing the `spaces` style in `whitespace-style`:

```emacs-lisp
;;                                            v
(setq whitespace-style '(face tabs tab-mark spaces space-mark trailing lines-tail))
```

> 2. Why there are dots in the line number

whitespace-mode tells Emacs to replace all spaces. A workaround is simply to use the unicode character `\u2002` (which looks like a space) in the line numbers:

```emacs-lisp
(defvar doom-ui-nlinum-lpad 4)
(defvar doom-ui-nlinum-rpad 1)
(defvar doom-ui-nlinum-spacer ?\u2002)

(defun doom-nlinum-format-fn (line width)
  "A more customizable `nlinum-format-function'. See `doom-ui-nlinum-lpad',
`doom-ui-nlinum-rpad' and `doom-ui-nlinum-spacer'."
  (let ((str (number-to-string line)))
    (setq str (concat (make-string (max 0 (- doom-ui-nlinum-lpad (length str)))
                                    doom-ui-nlinum-spacer)
                      str
                      (make-string doom-ui-nlinum-rpad doom-ui-nlinum-spacer)))
    (put-text-property 0 (length str) 'face
                        (if (and nlinum-highlight-current-line
                                (= line nlinum--current-line))
                            'nlinum-current-line
                          'linum)
                        str)
    str))

;; Make nlinum actually use it!
(setq nlinum-format-function #'doom-nlinum-format-fn)
```

-----

Thanks for bringing this to my attention. I've fixed it in my config.

**Comment by hlissner** [comment]
Whoops, forgot the third:

> 3. To get specific characters for newlines (BOX DRAWINGS LIGHT DOWN AND LEFT) and VERTICAL LINE between two spaces:

The first can be done by changing `whitespace-display-mappings`

```emacs-lisp
(setq-default 
 whitespace-display-mappings
 '((tab-mark ?\t [?› ?\t])
   (newline-mark 10 [?\u2510 10])   ;; ?\u2510 is the important change
   (space-mark 32 [183] [46])))
```

I'm uncertain if that's the right unicode code though.

As for VERTICAL LINE between two spaces, I'm afraid you can't do this with whitespace-mode, but perhaps something like [Highlight-Indentation](https://github.com/antonj/Highlight-Indentation-for-Emacs) could help?
