### ISSUE TITLE
typo in line 195 of core-modeline.el

### ISSUE THREAD

**Issue by apierz** [hlissner/.emacs.d#11]
Hi, I love your mode-line!

When updating my version with the recent changes, I noticed an error that will prevent the modeline from rendering.

On line 195 you have `aif` but it should be `if`.

**Comment by hlissner** [comment]
Actually `aif` is an alias for `anaphoric-if` in `amorphic.el`, but I don't like the additional dependency either, so I'll refactor it out for a normal `if` in a moment.

**Comment by apierz** [comment]
Gotcha, I'd never heard of amorphic.el before.
