### ISSUE TITLE
Q: Buffer automatically modified on open

### ISSUE THREAD

**Issue by Luladjiev** [hlissner/.emacs.d#110]
In my config I've disabled indentation highlight because of inject-whitespace package (ESLint was showing errors because of the white space until I save the file which I didn't like)

However I've noticed that every time I open a file it's already modified. Is it possible that there is something from the inject-whitespace which is causing this behavior or I didn't disable the highlight correctly?

Here is a link to the disablement in my config
https://github.com/Luladjiev/.emacs.d/blob/master/modules/private/luladjiev/config.el#L13

**Comment by hlissner** [comment]
What happens is you disabled highlight-indentation-mode after it had already been enabled. `doom|init-highlight-indentation` (poorly named, I know) -- which is attached to highlight-indentation-mode-hook -- injects whitespace on activation and deletes whitespace on deactivation, "modifying" the buffer.

So you can cut if off at the root (and this way still have highlight indentation):

```emacs-lisp
(remove-hook 'highlight-indentation-mode-hook #'doom|init-highlight-indentation)
```

Or you can entirely remove highlight-indentation-mode from javascript-mode:

```emacs-lisp
(remove-hook 'javascript-mode-hook #'highlight-indentation-mode)
```

**Comment by Luladjiev** [comment]
Those remove-hooks didn't work for me.

**Comment by hlissner** [comment]
I presume you placed one of those into that js2-mode-hook. That won't work; it's already loaded by then. You have to put them in an `after!` block instead:

```emacs-lisp
(after! highlight-indentation
  (remove-hook 'highlight-indentation-mode-hook #'doom|init-highlight-indentation))
```

or

```emacs-lisp
(after! js2-mode
  (remove-hook 'js2-mode-hook #'highlight-indentation-mode))
```

**Comment by Luladjiev** [comment]
Ah I see, now it worked, closing the issue.
