### ISSUE TITLE
A way to inhibit git-gutter-mode?

### ISSUE THREAD

**Issue by bandresen** [hlissner/.emacs.d#114]
Hey,

I think because of the `+evil-esc-hook` git-gutter-mode will enable itself even if it was explicitly disabled using `M-x git-gutter-mode RET`

It can slow down very large files that you may want to keep under version control but are prohibitively slowed down if git-gutter tries to update them. (200kb+ files.)

best regards,
benny

**Comment by hlissner** [comment]
Ah, good catch. Just pushed a fix to prevent that. Let me know that it works for you!
