### ISSUE TITLE
File mode specification error: (error lisp nesting exceeds ‘max-lisp-eval-depth’)

### ISSUE THREAD

**Issue by Luladjiev** [hlissner/.emacs.d#115]
With the latest changes when I open a javascript file I get this error and Prog mode is activated instead of js2-mode. It may happen after a while, not always. 

When I get the error and try ```M-x js2-mode``` I get the same error and the mode stays at Prog so I suppose it's something related to lang/javascript changes.

**Comment by hlissner** [comment]
Found and fixed!

**Comment by Luladjiev** [comment]
Great, no issues so far, closing the issue!
