### ISSUE TITLE
Missing character?

### ISSUE THREAD

**Issue by angerman** [hlissner/.emacs.d#116]
So after giving this a try, I get a missing character in the mode line:

<img width="703" alt="screen shot 2017-06-19 at 10 41 47 pm" src="https://user-images.githubusercontent.com/40449/27305089-9629a828-5540-11e7-9714-be1f978e192d.png">

Any suggestions?

**Comment by angerman** [comment]
Answering my own question: (after finding https://github.com/hlissner/.emacs.d/tree/master/modules/ui/doom-modeline)

```
brew tap caskroom/fonts
brew cask install font-fira-{sans,mono} font-dejavu-sans
```
and
```
M-x all-the-icons-install-fonts
```
are needed.

**Comment by ammkrn** [comment]
All of the closed duplicates seem to have been solved by `M-x all-the-icons-install-fonts`, but this hasn't resolved the issue for me. I'm on Ubuntu 18.04/Emacs 26.3 with a new Doom installation.
`M-x all-the-icons-install-fonts` seems to execute without any errors, returning two messages :
`fonts downloaded, updating font cache`, and `Successfully installed all-the-icons fonts to /home/<user>/.local/share/fonts`. I do indeed see `all-the-icons.tff` where the output said it would be, but after restarting Doom, the icons in the modeline are still broken. I also tried `doom sync` and `doom refresh` after the fact.

**Comment by hlissner** [comment]
> I also tried doom sync and doom refresh after the fact.

These two commands are aliases. No need to use them both.

> but this hasn't resolved the issue for me

The two common causes for this are:

1. The download process failed silently (usually downloading empty or corrupted font files). Check the font files; very small files (<5kb) are suspect.
2. The font cache wasn't actually updated.

In any case, you'll find the fonts here: https://github.com/domtronn/all-the-icons.el/tree/fonts

Try downloading and installing them manually. It is available to Arch Linux users via the `ttf-all-the-icons` package, and NixOS users via the `pkgs.emacs-all-the-icons-fonts` package as well. I'm not sure if it's package for Ubuntu.

**Comment by ammkrn** [comment]
Thanks for the quick response. FWIW the only one that didn't download correctly was `material-design-icons.tff` which had a size of 0. The other five have the same sha256sum as the files from the repo.

For anyone else that runs into this on Ubuntu, the steps to fix were :
1. Clone the [all-the-icons repo](https://github.com/domtronn/all-the-icons.el) anywhere that's convenient
2. Delete the font(s) in question (they have the same names the files in `all-the-icons/fonts`) from wherever Doom downloaded them to, probably `.local/share/fonts`. 
3. copy the `.ttf` files from `all-the-icons.el/fonts` into `.local/share/fonts`
