### ISSUE TITLE
Using a custom theme

### ISSUE THREAD

**Issue by aminb** [hlissner/.emacs.d#117]
I haven't been able to figure out how to use a custom theme from a package other than `doom-themes`.

Adding `(package! material-theme)` in my `packages.el` file and then running `make` will attempt to install the package. But then I don't know where to actually set the theme.

Doing `(setq +doom-theme 'material-light)` in `config.el` seems to be too late, and in `init.el` of the layer seems to be too early.

**Comment by vsr625** [comment]
First you have to disable the doom theme from your init.el, by commenting 'doom' in the ui section. 
Then you can load the theme normally in your init.el using normal methods. Make sure that you run "make compile" after making changes to your .el files. (setq +doom-theme 'material-light) this option is for selecting the color scheme within the doom theme, author provides many different color schemes, you can select any one of those using that option, check here [doom](https://github.com/hlissner/emacs-doom-themes) for the available color schemes.

**Comment by aminb** [comment]
@vsr625 Thanks. It'd be nice if I could get away without disabling the whole `doom` module in `:ui` though; as it does a whole bunch of other things aside from `(def-package! doom-themes ...)` that I'd like to keep.

Any thoughts @hlissner?

**Comment by hlissner** [comment]
You're right, it's not ideal. I'm working on a solution to decouple theme/font loading from ui/doom which should be done sometime today. I'll keep you posted!

**Comment by hlissner** [comment]
I've pushed a fix for this and introduced a couple new variables. The relevant one being `doom-theme`. You can set that anywhere, and it will take effect at the end of startup.

If you'd like to disable `doom-themes`, you can do so from your private init.el file:

```emacs-lisp
(def-package-hook! doom-themes :disable)
```

And you can prevent doom-themes from being installed at all from your private packages.el:

```emacs-lisp
(package! doom-themes :ignore t)
```

Let me know if this gives you any trouble!

**Comment by aminb** [comment]
Thanks for the patch. Unfortunately, it doesn't seem to be working properly:

Having `(package! material-theme)` in the `packages.el` file of my module, and `(setq doom-theme 'material-light)` doesn't seem to be working. Emacs starts up with the following warning, and no themes applied:

`Error (doom-init-hook): error in ’doom|init-ui’ -> Unable to find theme file for ‘material-light’`

**Comment by hlissner** [comment]
You need `(require 'material-theme)` in your config.el for Emacs to know where to find the theme.

**Comment by aminb** [comment]
Oh you're right, I totally forgot about `require`ing. *facepalms*

Awesome, thanks!
