### ISSUE TITLE
No Evil

### ISSUE THREAD

**Issue by UtamaruMonster** [hlissner/.emacs.d#132]
Good day.

I'm not a Vim converted. So is it possible to make Evil as an option, because commenting out Evil in init.el will not do. So project text search :ag and so on can work without Evil.

Thank you.

**Comment by hlissner** [comment]
Commenting evil out in init.el should be enough. If that isn't working for you, a common cause is that you are running byte-compiled Doom. Did you run `make compile` or `make core` before removing evil from init.el? If so, use `make clean` to remove byte-compiled files, then try again.

I'm not sure I understand about `:ag`. Without evil you don't have access to ex commands (like `:ag`), but you still have access to `M-x counsel-ag` (which is what `:ag` uses under the hood). Same for `counsel-rg`. Is that what you mean?

**Comment by UtamaruMonster** [comment]
About the :ag. Yes the counsel-ag does the job. Thank you. All works. 
Maybe we can get a noob friendly documentation on how-to features. 
And yes i did all the make processes :D
