### ISSUE TITLE
apply: Symbol’s function definition is void: +workspaces*autosave-real-buffers

### ISSUE THREAD

**Issue by matthewgraybosch** [hlissner/.emacs.d#133]
I just started getting this when trying to save and quit after pulling the latest from master.

> apply: Symbol’s function definition is void: +workspaces*autosave-real-buffers

The only way for me to get out of emacs is to send SIGKILL to the process.

```make doctor``` shows no issues.

~~~
matthew@koschei:~/.emacs.d$ make doctor
DOOM Doctor
Running Emacs v25.2.2, commit 4591bb003296978ba8a9772e3854a91b4c646fed

Compiled with:
  XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GCONF GSETTINGS
  NOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB
  TOOLKIT_SCROLL_BARS GTK3 X11 MODULES
uname -a:
  Linux koschei 4.8.0-34-generic #36~16.04.1-Ubuntu SMP Wed Dec 21
  18:55:08 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

----

Everything seems fine, happy Emacs’ing!
~~~

**Comment by hlissner** [comment]
If you run `make autoloads`, does that fix the problem?

**Comment by matthewgraybosch** [comment]
```make autoloads``` solved the problem. Thanks.

**Comment by hlissner** [comment]
Glad to hear it. As a general rule of thumb, run `make` whenever you update from master. That should help you avoid these types of issues in the future.
