### ISSUE TITLE
Using company-mode for writing English prose?

### ISSUE THREAD

**Issue by matthewgraybosch** [hlissner/.emacs.d#134]
One thing I liked about Spacemacs was that its autocompletion setup even worked when writing plain English text, and not just for code.

I'd like to enable similar functionality in Doom Emacs, but the following in my private init.el isn't cutting it.

~~~(require 'company)
(setq company-idle-delay 0.1
      company-minimum-prefix-length 3
      company-backends '(company-capf
                         company-ispell
                         company-yasnippet
                         company-etags
                         company-elisp
                         company-files
                         company-gtags))

~~~

Any suggestions?

**Comment by hlissner** [comment]
Unfortunately, I don't know what company backends spacemacs uses in text modes. It's probably the default, in which case, try again with `company-dabbrev` and `company-abbrev` in that list.

**Comment by matthewgraybosch** [comment]
Thanks! Commit 3801da0 helped, but I still had to edit the module config and add the following to make company work the way I like it. No biggie, though. 

```
company-idle-delay 0.1
company-minimum-prefix-length 2
```

I'll close this issue, but it possible to create a ```company-with-popups``` module that inherits from the ```company``` module while enabling the completion popup? If so, people could choose between company with popups and company with manual completion by loading the appropriate module from init.el.

**Comment by mandarvaze** [comment]
Adding the following to my `config.el` helped me getting completion for the `text-mode` (Adding here, in case someone else comes looking for help)
```elisp
(set-company-backend! 'text-mode 'company-ispell 'company-dabbrev)
```

**Comment by hlissner** [comment]
To follow up, I've rewritten how `set-company-backend!` works, so that it now can be used with parent and minor modes. These are the defaults:

```elisp
(defvar +company-backend-alist
  '((text-mode :derived (company-dabbrev company-yasnippet))
    (prog-mode :derived (:separate company-capf company-yasnippet))
    (conf-mode :derived company-capf company-dabbrev-code company-yasnippet))
  "An alist matching modes to company backends. The backends for any mode is
built from this.")
```

All text-modes now fall back on `(company-dabbrev company-yasnippet)`, which should suffice for prose (and thus, resolve this issue). I may add company-ispell to that.

----

For posterity, here is how to set backends for a parent mode like text-mode or prog-mode:

```elisp
(set-company-backend! :derived 'text-mode 'company-dabbrev 'company-yasnippet)
```

Otherwise, it works as usual for exact major or minor modes:

```elisp
  (set-company-backend! 'js2-mode 'company-tide 'company-yasnippet)

  (set-company-backend! 'sh-mode
    '(company-shell :with company-yasnippet))

  (set-company-backend! '(c-mode c++-mode)
    '(:separate company-irony-c-headers company-irony))

  (set-company-backend! 'sh-mode nil) ; unsets backends for sh-mode

  ;; For minor modes. 
  (set-company-backend! 'anaconda-mode 'company-anaconda)
```

These backends cascade in order of activation. So these backends:

```elisp
(set-company-backend! 'python-mode 'a 'b)
(set-company-backend! 'anaconda-mode 'c)
```

Will result in `(c a b ...)` as your company backends in a python-mode buffer with anaconda-mode enabled.
