### ISSUE TITLE
Company backends macro updates global variable & does not exclude duplicates

### ISSUE THREAD

**Issue by gilbertw1** [hlissner/.emacs.d#135]
I was using the updates you made to the ```company-backends``` setting (thanks for adding that by the way!), and I noticed some weird behavior. Two things I noticed:

1) Every time a new buffer was loaded, it's additional backends were being appended the the global ```company-backends``` var, putting all the modes backends into the global list.

2) This resulted in tons of duplicates backends being added to the list.

After loading all my perspectives, I had about 30 separate entries in the ```company-backends``` list. Previously this wasn't as noticeable, because ```cl-pushnew``` was not adding duplicate backends, as is happening with ```append```. This explains why I ALWAYS noticed ```company-restclient``` in the backends list (I always keep a .rest file open in most of my api projects).

I was able to work around both of these issues (granted 2 is only really a problem because of 1) by:

1) Changing ```setq``` to ```setq-local``` [here](https://github.com/hlissner/.emacs.d/blob/master/modules/completion/company/config.el#L14):
```elisp
  (setq-local company-backends (append (list ,@backends) company-backends))))
```

2) Bringing back ```cl-pushnew```:

```elisp
  (make-local-variable 'company-backends)
  ,@(cl-loop for backend in backends
    collect `(cl-pushnew ',backend company-backends :test #'equal))))
```

Not sure how high of quality those fixes are, but they illustrate where the problem lies pretty well.

Thanks!

**Comment by hlissner** [comment]
Yikes, good catch! I've been pretty careless with :company-backend. Perhaps it's about time I started writing unit tests for this module!

In any case, thanks for letting me know. It should work fine now.

**Comment by gilbertw1** [comment]
Awesome, thanks!
