### ISSUE TITLE
Enter insert mode when editing in `org-capture`

### ISSUE THREAD

**Issue by gilbertw1** [hlissner/.emacs.d#138]
Hey! I'm currently on the "learning org-mode step" of my Emacs spiritual journey. I've been slowly reassembling your org-mode implementation, and one thing I noticed that might be an improvement is to automatically enter insert mode after selecting a capture template to edit.

I achieved this by adding the following hook (in the `org|init-capture`):

```elisp
    (add-hook 'org-capture-mode-hook 'evil-insert-state)
```

Your org-mode implementation is extremely well thought out, and I really appreciate it more and more as I dig into org. Anyways, just thought I'd share this tidbit if you are interested.

**Comment by hlissner** [comment]
Thanks! org has been (and still is) the toughest part of this whole config, and isn't even close to finished yet.

In any case, I liked the suggestion so I pushed it upstream. Also, sorry for the commit spam, I was a bit overeager with that force push! Won't happen again.

**Comment by gilbertw1** [comment]
That totally makes sense ... I feel like the hardest part to using org-mode is deciding how you want to use it. There's so many different possibilities and workflows, I keep finding myself with decision paralysis trying to move forward fleshing out the config. I've read / watched four or five different blog posts / screencasts and everyone uses it an entirely different way. 

No worries on the commits, small price to pay for getting so much awesome stuff for free :)
