### ISSUE TITLE
Scratch buffer won't open if region is not currently selected

### ISSUE THREAD

**Issue by gilbertw1** [hlissner/.emacs.d#139]
Hey,

After the recent changes to ```doom/scratch-buffer```, specifically after adding ```(interactive "rP")``` the scratch buffer fails to load with with the error message: ```The mark is not set now, so there is no region``` if text is not currently selected.

I've worked around this issue in [this commit](https://github.com/gilbertw1/bmacs/commit/95791e33545e126ee9d1d63d34227ff94424b4f2) by manually checking if a region is active and appending the selected region to the scratch buffer if it is.

**Comment by hlissner** [comment]
Ah, good catch! I've pushed a fix.
