### ISSUE TITLE
Moving to open popups

### ISSUE THREAD

**Issue by UndeadKernel** [hlissner/.emacs.d#141]
I guess this is more a question than an issue.

How do you move the cursor to an open popup? Currently, when switching windows with C-x o (other-window), buffers defined as unreal (like popups) are not considered as candidates for switching.

For example, if I open the help buffer that describes de major and minor modes (C-h m [describe-mode]), how would you switch between the help popup and the main buffer window?

**Comment by hlissner** [comment]
I've advised `evil-window-{up,left,right,down}` and `windmove-{up,down,left,right}` to address this, but I realize that is geared toward evil users. In your case, you don't have many options, so I added a `doom/other-popup` command. You could bind this to `C-x p` with `(global-set-key (kbd "C-x p") #'doom/other-popup)`.

This is currently in the `develop` branch, but will make its way onto master over the weekend.

**Comment by hlissner** [comment]
This is now in master, so I'll consider this resolved.

**Comment by chriselrod** [comment]
`C-x p` can jump to the popup, but then how do we jump back?
