### ISSUE TITLE
'make run' runs the wrong emacs configuration

### ISSUE THREAD

**Issue by UndeadKernel** [hlissner/.emacs.d#142]
I currently have ~/.emacs.d pointing to ~/emacses/doomv1/.emacs.d (which is a modified version of DOOM emacs v1). I have DOOM emacs v2 in the folder ~/emacses/doomv2/.emacs.d . When running "make run" from the v2 folder, DOOM emacs v1 is loaded instead.

To run version 2, I need to be in its folder and use the command:
"HOME=~/emacses/doomv2 emacs"

I'm not sure how to debug this as all variables are setup correctly in the Makefile, yet the wrong files are loaded. Is there a weird cache mechanism (related to compiling) that is not being taken into consideration?

**Comment by hlissner** [comment]
Ah, good catch. The `run` task uses the `emacs` binary straight, without `-q` to prevent ~/.emacs.d/init.el from being loaded. It _should_ be:

```makefile
run:
	@$(EMACSI) $(EMACS_FLAGS) -l init.el
```

The fix will be up soon.

**Comment by hlissner** [comment]
Done. Feel free to reopen this if the problem returns.

**Comment by UndeadKernel** [comment]
The fix works, though, it uses one two many $(EMACS_FLAGS). The variable $EMACSI already includes the flags. The run rule should instead be:

```
run:
	@$(EMACSI) -l init.el
```

**Comment by hlissner** [comment]
Whoops! You're right, I was too hasty. I'll follow up with another commit soon.
