### ISSUE TITLE
Consider notmuch's buffers as real

### ISSUE THREAD

**Issue by aminb** [hlissner/.emacs.d#143]
I use `notmuch` for email, and I'm pretty sure all of its buffers follow a `\*notmuch-.*\*` naming convention. Examples:

- `*notmuch-hello*`
- `*notmuch-saved-search-unread*`
- `*notmuch-tree-tag:unread*`

How can I tell doom to consider notmuch's buffers as real?

**Comment by hlissner** [comment]
The variable `doom-real-buffer-functions` are a list of functions that are checked if the current buffer is real. If any function returns non-nil, it's real. 

So something like this would help:

```emacs-lisp
(defun notmuch-buffer-p (buffer)
  (string-match-p "^\\*notmuch-" (buffer-name buffer)))
(push #'notmuch-buffer-p doom-real-buffer-functions)
```

**Comment by aminb** [comment]
Awesome, that did it. Thank you!
