### ISSUE TITLE
Cannot open load file: No such file or directory, auth-store-pass

### ISSUE THREAD

**Issue by chriskaukis** [hlissner/.emacs.d#146]
I just cloned and tried to follow your readme. I am getting the following error when trying to make compile, make core, or even run emacs:

```
(doom-initialize-packages) file-missing in modules/tools/password-store/config.el: Cannot open load file: No such file or directory, auth-store-pass
make: *** [autoremove] Error 255
```

Emacs Version:

```
➜  .emacs.d (master) ✔ emacs --version
GNU Emacs 26.0.50
Copyright (C) 2017 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
```

`which emacs`

```
➜  .emacs.d (master) ✔ which emacs
/usr/local/bin/emacs
```

I installed using homebrew using the instruction for installing emacs-plus on the Spacemacs page. Should I perhaps try re-installing? Do you suggest a certain repo or version of emacs?

OS:

```
macOS Sierra
Version 10.12.5
```

I dug into this as much as I can. I'm kind of new to emacs in general, but have used Spacemacs quite a bit. It appears emacs 26+ has this included and has special load instructions. I looked at the config.el file in the module directory and it looks correct. So, I'm kind of at lost at the moment debugging until later tonight. 

For now since I don't need the package and have never even heard or used it I have commented it out. Hoping you can help me figure out what's up though.

```
DOOM Doctor
Running Emacs v26.0.50, commit 38f842f186cc625e3f62795be90891f7feb924fe

Compiled with:
  JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB
  TOOLKIT_SCROLL_BARS NS MODULES
uname -a:
  Darwin Alucard 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14
  16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64

----

peculiar error
make: *** [doctor] Error 255
```

**Comment by chriskaukis** [comment]
If anyone else has a problem I uninstalled and installed using the default homebrew emacs. It seems to work now. 

```

**Comment by hlissner** [comment]
The `tools/password-store` module assumed that the `auth-store-pass` package was built into Emacs 26+, but it turns out not to always be the case. Switching back to Emacs 25 would fix this, but I've added a fix in a recent commit so that future Emacs 26 users don't experience this error.

**Comment by ShashankaNataraj** [comment]
![image](https://user-images.githubusercontent.com/650317/40828893-8367cc04-659f-11e8-88d8-bb24f603abec.png)
@hlissner Im still seeing this error on 25.3

**Comment by hlissner** [comment]
@ShashankaNataraj I cannot reproduce this. Does `make autoloads` (And if you've byte-compiled, `make clean`) resolve the issue?

**Comment by ShashankaNataraj** [comment]
@hlissner Hi, I havent byte compiled. I tried to run `make autoloads` and the corresponding output was:

`Deleted old autoloads.el
✓ Scanned core/autoload/ui.el
✓ Scanned core/autoload/test.el
✓ Scanned core/autoload/system.el
✓ Scanned core/autoload/scratch.el
✓ Scanned core/autoload/popups.el
✓ Scanned core/autoload/packages.el
✓ Scanned core/autoload/minibuffer.el
✓ Scanned core/autoload/message.el
✓ Scanned core/autoload/menu.el
✓ Scanned core/autoload/memoize.el
✓ Scanned core/autoload/help.el
✓ Scanned core/autoload/editor.el
✓ Scanned core/autoload/debug.el
✓ Scanned core/autoload/buffers.el
✓ Scanned modules/feature/eval/autoload/eval.el
✓ Scanned modules/feature/eval/autoload/evil.el
✓ Scanned modules/feature/eval/autoload/repl.el
✓ Scanned modules/feature/evil/autoload/evil-mc.el
✓ Scanned modules/feature/evil/autoload/evil.el
✓ Scanned modules/feature/evil/autoload/files.el
✓ Scanned modules/feature/evil/autoload/folds.el
✓ Scanned modules/feature/jump/autoload/evil.el
✓ Scanned modules/feature/jump/autoload/jump.el
✓ Scanned modules/feature/services/autoload.el
✓ Scanned modules/feature/snippets/autoload/evil.el
✓ Scanned modules/feature/snippets/autoload/snippets.el
✓ Scanned modules/feature/version-control/autoload.el
✓ Scanned modules/feature/workspaces/autoload/evil.el
✓ Scanned modules/feature/workspaces/autoload/workspaces.el
✓ Scanned modules/completion/company/autoload.el
✓ Scanned modules/completion/ivy/autoload/evil.el
✓ Scanned modules/completion/ivy/autoload/ivy.el
✓ Scanned modules/ui/doom-dashboard/autoload.el
✓ Scanned modules/ui/hl-todo/autoload.el
✓ Scanned modules/ui/nav-flash/autoload.el
✓ Scanned modules/ui/evil-goggles/autoload.el
✓ Scanned modules/tools/eshell/autoload/eshell.el
✓ Scanned modules/tools/eshell/autoload/evil.el
✓ Scanned modules/tools/gist/autoload/evil.el
✓ Scanned modules/tools/gist/autoload/gist.el
✓ Scanned modules/tools/impatient-mode/autoload.el
✓ Scanned modules/tools/make/autoload.el
✓ Scanned modules/tools/neotree/autoload.el
✓ Scanned modules/tools/password-store/autoload.el
✓ Scanned modules/tools/term/autoload.el
✓ Scanned modules/tools/tmux/autoload/evil.el
✓ Scanned modules/tools/tmux/autoload/tmux.el
✓ Scanned modules/tools/upload/autoload.el
✓ Scanned modules/lang/cc/autoload.el
✓ Scanned modules/lang/emacs-lisp/autoload.el
✓ Scanned modules/lang/go/autoload.el
✓ Scanned modules/lang/java/autoload.el
✓ Scanned modules/lang/javascript/autoload.el
✓ Scanned modules/lang/julia/autoload.el
✓ Scanned modules/lang/lua/autoload.el
✓ Scanned modules/lang/markdown/autoload.el
✓ Scanned modules/lang/org/autoload/evil.el
✓ Scanned modules/lang/org/autoload/org-attach.el
✓ Scanned modules/lang/org/autoload/org-babel.el
✓ Scanned modules/lang/org/autoload/org-capture.el
✓ Scanned modules/lang/org/autoload/org-link.el
✓ Scanned modules/lang/org/autoload/org-present.el
✓ Scanned modules/lang/org/autoload/org.el
✓ Scanned modules/lang/org/autoload/tables.el
✓ Scanned modules/lang/php/autoload.el
✓ Scanned modules/lang/plantuml/autoload.el
✓ Scanned modules/lang/python/autoload.el
✓ Scanned modules/lang/rust/autoload.el
✓ Scanned modules/lang/sh/autoload.el
✓ Scanned modules/lang/web/autoload/css.el
✓ Scanned modules/lang/web/autoload/evil.el
✓ Scanned modules/lang/web/autoload/html.el
✓ Scanned modules/private/default/autoload/default.el
✓ Scanned modules/private/default/autoload/evil.el
Finished generating autoloads.el!`

I just checked out a fresh copy of the doom config. I still see the same error.

**Comment by hlissner** [comment]
@ShashankaNataraj Are you on Doom's `develop` branch?

**Comment by ShashankaNataraj** [comment]
@hlissner 

![image](https://user-images.githubusercontent.com/650317/43825768-38c82b0e-9b13-11e8-94a5-1c0948b9c8d9.png)

**Comment by hlissner** [comment]
Ah, that explains it. Please switch to the `develop` branch. `master` is currently _very_ outdated (by ~7 months and 2800+ commits). Many of these issues have been resolved there. I'm currently cleaning up the new documentation branch and will be merging it as soon as I'm back home travelling (at the end of this week).

**Comment by ijacquez** [comment]
I just encountered this issue. Would it be possible to switch the default branch from `master` to `develop`?

That way, a `git clone` would already have the `develop` branch checked out.
