### ISSUE TITLE
Failing to compile project (specifically map! macro)

### ISSUE THREAD

**Issue by gilbertw1** [hlissner/.emacs.d#147]
Hey! After pulling the latest commits I noticed that I'm hitting errors compiling, specifically usages of the ```map!``` macro. Here's a little output:

![errors](http://drop.bryan.sh/fOykzI0HQs.png)

I'm noticing similar errors anywhere the ```map!``` macro is used. I've reproduced this as well on a clean checkout of the doom emacs config. I haven't done much digging, but if I come up with any more details I'll post them here.

Thanks!

**Comment by gilbertw1** [comment]
Small update: I found that I can make the problem go away if I add ```(require 'core-keybinds)``` to the beginning of the function: ```doom-initialize-autoloads```.

**Comment by hlissner** [comment]
Whoops, looks like my recent changes in `doom-initialize-packages` were to blame (doom core files weren't being loaded). I've fixed it now. Feel free to reopen if it hasn't fixed the problem.
