### ISSUE TITLE
Startup error: Invalid function: +ivy-do-action!

### ISSUE THREAD

**Issue by gilbertw1** [hlissner/.emacs.d#148]
Hey, I've pulled up to the latest and I'm noticing the following startup error:

![error](http://drop.bryan.sh/s4MxsHXsfr.png)

I'm guessing some changes in the load order are resulting in the keybindings being evaluated prior to the macro ```+ivy-do-action!``` in ivy's ```config.el```.

Thanks!

**Comment by hlissner** [comment]
Odd. I had that error just before https://github.com/hlissner/.emacs.d/commit/6a5bd216e5c06a88c4ec2795337e25cd8f131a48, and can't reproduce it after. I'm looking into it.

**Comment by bandresen** [comment]
I also have this issue, I went through git bisect and the first bad commit is ea4d0a50cb05545dfc839dc55957c0a3fef1f4cb

**Comment by hlissner** [comment]
I've reverted a change that made doom's non-interactive initialization less aggressive (thus causing it to miss macro definitions in modules, like `+ivy-do-action!`). This shouldn't occur anymore.
