### ISSUE TITLE
undo-tree not included in core/packages.el ?

### ISSUE THREAD

**Issue by UndeadKernel** [hlissner/.emacs.d#149]
One of the compilation errors I see is related to undo-tree:
```
In toplevel form:
core/core-editor.el:244:1:Error: Cannot open load file: Not a directory, undo-tree
Failed to compile core/core-editor.el
```
Is it possible that the package "undo-tree" is missing from "core/packages.el" or is the package is missing on purpose?

**Comment by hlissner** [comment]
Ah, my bad. `undo-tree` is one of `evil`'s dependencies and I took that for granted.

I've added it to core/packages.el
