### ISSUE TITLE
defuns-smartparens.el introduces a function that is never used

### ISSUE THREAD

**Issue by UndeadKernel** [hlissner/.emacs.d#15]
I just noticed the function "doom/sp-insert-yasnippet" in the file "core/defuns/defuns-smartparens.el" which is not used anywhere. 

Could this function have been left stranded there after a past refactoring?

**Comment by hlissner** [comment]
Yes, and [very recently too](https://github.com/hlissner/.emacs.d/commit/c9b69efa1104b4ef845c4c4c56c28d62010e26a7). Though I intend to tweak smartparens more, I don't expect to use doom/sp-insert-yasnippet again. I'll delete it in the next push.
