### ISSUE TITLE
Compilation error in modules/lang/latex/config.el

### ISSUE THREAD

**Issue by UndeadKernel** [hlissner/.emacs.d#162]
When running `make compile`, the following error is observed:
```
In toplevel form:
modules/lang/latex/config.el:51:9:Error: not a valid state: 76
```
This error is being triggered by the following mappings in line 62:
```
    (map! :Le "j"   #'next-line
          :Le "k"   #'previous-line
          :Le "q"   #'kill-buffer-and-window
          :Le "ESC" #'kill-buffer-and-window)
```

The error refers to state "76", which is ASCII for "L". If the "L" letters are removed from the bindings, the file compiles as expected.

This implies that we might be dealing with the issue that the "L" state is being parsed incorrectly (maybe) by the "map!" macro.

Anyhow, what is the purpose of the "L" state? I don't use evil and I'm not familiar with all vim related modes (states). By the way, I did check compiling with evil enabled and disabled (in init.el), which of course should not matter as emacs is run with "--batch" and the init.el file is supposedly ignored. Correct?

**Comment by hlissner** [comment]
You are correct, that the L was parsed incorrectly, causing the error.

The :L state was meant to denote a buffer-local binding. It wasn't a good idea, in hindsight, since it is unlike the other states, so I replaced it with a :local property. i.e.

```emacs-lisp
(map! :local
          :e "j"   #'next-line
          :e "k"   #'previous-line
          :e "q"   #'kill-buffer-and-window
          :e "ESC" #'kill-buffer-and-window)
```

This also fixes your problem. Feel free to reopen this if that isn't the case.
