### ISSUE TITLE
Modeline left hand-side doesn't appear in terminal mode

### ISSUE THREAD

**Issue by amoriello** [hlissner/.emacs.d#170]
Hi

the left hand-side of modeline doesn't appear in terminal mode.

From what I see,

***
**modules/ui/doom-modeline/config.el**
```lisp

;; The bar regulates the height of the mode-line in GUI Emacs.
(def-modeline-segment! bar
  (when (display-graphic-p)
    (+doom-modeline--make-xpm
     (face-background (if (active)
                          'doom-modeline-bar
                        'doom-modeline-inactive-bar)
                      nil t)
     +doom-modeline-height
     +doom-modeline-bar-width)))


...



(def-modeline! main
  (bar matches " " buffer-info "  %l:%c %p  " selection-info)
  (buffer-encoding major-mode vcs flycheck))
```

❗️   bar returns nil when in terminal mode

***

**core/core-ui.el**
```lisp
(defsubst doom--prepare-modeline-segments (segments)
  (cl-loop for seg in segments
           if (stringp seg)
            collect seg
           else
            collect (list (intern (format "doom-modeline-segment--%s" (symbol-name seg))))))

(defmacro def-modeline! (name lhs &optional rhs)
  "Defines a modeline format and byte-compiles it. NAME is a symbol to identify
it (used by `doom-modeline' for retrieval). LHS and RHS are lists of symbols of
modeline segments defined with `def-modeline-segment!'.

Example:
  (def-modeline! minimal
    (bar matches \" \" buffer-info)
    (media-info major-mode))
  (doom-set-modeline 'minimal t)"
  (let ((sym (intern (format "doom-modeline-format--%s" name)))
        (lhs-forms (doom--prepare-modeline-segments lhs))
        (rhs-forms (doom--prepare-modeline-segments rhs)))
...
```
***

❗️ when `def-modline!` process the `lhs` part of the modeline, `doom--prepare-modeline-segments` doesn't expect any of the segments `seg` to be `nil`.

***

Making `def-modeline-segment! bar` return an empty string `""` instead of `nil` when not in GUI mode fixes the issue, but I'm pretty sure this isn't the right fix 😜 (thus, not proposing any PR, since I'm not fluent enough in lisp - working on it - ).

You're doing great stuff here, this project actually pushes me to learn lisp.

Hope this helps.

Thanks!

**Comment by bandresen** [comment]
Seems to be the correct fix as far as I can see, as bar is responsible for the height of the modeline and a textual interface can only have a height of whatever font is choosen by the terminal.

Functionality that "expands" the `bar` aspect like recording a macro still works after this patch in both GUI and TUI.

**Comment by hlissner** [comment]
I believe this has been fixed, thanks to @bandresen's PR, so I will close this. Feel free to reopen if that isn't the case.
