### ISSUE TITLE
Interest in doom-modeline change? (truncated paths)

### ISSUE THREAD

**Issue by bandresen** [hlissner/.emacs.d#172]
I changed the modeline a little bit. I use a lot of long paths and the relative to root paths aren't always enough to tell me immediately in which project I'm in so I built a fish shell directory truncate function.

This is what I came up with:
![](http://i.imgur.com/M4rUlSR.png)

I also use it in the eshell prompt:
![](https://gitlab.com/bennya/shrink-path.el/raw/screenshots/eshell-prompt.png)

It's not yet mature but I wanted to ask that if you're into it I will polish it up and do a PR.

**Comment by hlissner** [comment]
Sure, color me interested! I'd be happy to add it to both eshell and the modeline.
