### ISSUE TITLE
dump-jump package

### ISSUE THREAD

**Issue by rphillips** [hlissner/.emacs.d#179]
Henrik, have you seen the [dumb-jump](https://github.com/jacktasia/dumb-jump) package? It will use ag, rg, or grep to implement a jump. I haven't tried it, but it might make a good addition to your config.

**Comment by bandresen** [comment]
Included since April https://github.com/hlissner/.emacs.d/blob/4454226a424184086df5020c906af7936f161689/CHANGELOG.org#201-apr-8-2017

**Comment by rphillips** [comment]
Oh snap! Helps if I don't typo my grep as well. Thanks!
