### ISSUE TITLE
Yasnippet expansion is broken

### ISSUE THREAD

**Issue by UndeadKernel** [hlissner/.emacs.d#18]
It seems that the yasnippet expansion is not working as intended.

If I understand correctly, snippet expansion only occurs when some text is selected. If I open an elisp file, for example init.el, type in "def", select that word and then press tab; then an unrelated snippet is expanded.

**Comment by hlissner** [comment]
No selection is necessary. You type `def`, press tab and the snippet expands.

Make sure you have snippets installed. They're not included in this config. [I keep mine in a separate repo](https://github.com/hlissner/emacs-snippets). Run `make snippets` in `~/.emacs.d` to install them (or just clone them to `~/.emacs.d/private/snippets`) -- if you use them, I suggest you fork them; mine are tied closely to my own workflows and will change often.

Assuming you have snippets installed, these are the two main ways to use snippet expansion (`|` will represent the cursor, as well as the editable points you can cycle through after expansion):

+ `defun|` => <kbd>Tab</kbd> => `(defun fn-name| (|) |)`

+ `(message "Hi")` => select the form => <kbd>Tab</kbd> => select `defun` =>
   ```elisp
(defun fn-name|()
      (message "Hi")|)
```

This gif illustrates these two workflows:

![](http://v0.io/dl/snip.gif)

**Comment by UndeadKernel** [comment]
I must've been something messed up with my repository copy.
After loading the master branch from scratch and loading some snippets, it is back to working!
Quick questions: what tool(s) are you using for the animated gifs?

**Comment by hlissner** [comment]
Oh gosh, I'm so sorry i'm only noticing this message now! I'm actually still on the prowl for a good gif app. For the above, I used Quicktime Player (which has a screen recorder on Mac) and use [this script](https://github.com/hlissner/dotfiles/blob/v2.0/bin/mov2gif) to convert the resulting .mov file into a .gif.

You could use any screen recorder with that script, really. Haven't tried it with other video formats though.

Other alternatives:
+ https://github.com/colinkeenan/silentcast (linux)
+ http://www.cockos.com/licecap/ (win/osx)
