### ISSUE TITLE
Major mode specific bindings (+hydra)

### ISSUE THREAD

**Issue by bandresen** [hlissner/.emacs.d#180]
Hey Henrik,

I know keybindings are handled in private modules, but wouldn't it be good if there was a doom keymap created per major mode where you would just bind this dispatch function and you get access to a keymap that was prepared in the module?

The same could be done for local hydras where they make sense.

Basically similar to `+eval/repl` but in a bigger way.

**Comment by hlissner** [comment]
Technically, that's what the `:localleader` prefix is for (default is `SPC m`). I put (buffer|major-mode)-specific bindings there. Is that what you mean?

**Comment by bandresen** [comment]
It is what I mean. Haven't seen it much in the places I checked but it's used by mu4e for example.
Good to know!
