### ISSUE TITLE
unbalanced parenthesis despite active smartparens-mode

### ISSUE THREAD

**Issue by bandresen** [hlissner/.emacs.d#181]
Hey, the following situation is IMO a bug: (point is |)
```
|(foo)
```
now insert a `(`

what you get:
```
(|(foo)
```

what I expect to get:
```
(|)(foo)
```

I found that you modified () [] and {} to be more conservatively when auto-closing but I wasn't a big smartparens user before (paredit in the olden days and lispy more recently) so I don't know what behavior you didn't like, which caused you to change it.

If this isn't a bug but an idiosyncrasy :-) or the trade-off to fix this isn't worth it can you introduce a variable like `doom-smartparens-auto-close-conservatively`?

Thanks in advance!

**Comment by hlissner** [comment]
This is certainly an idiosyncracy. I'll move it to my private module. It is rare that I need a both delimiters next to non-whitespace; definitely personal preference!
