### ISSUE TITLE
make doctor says font isn't installed 

### ISSUE THREAD

**Issue by rphillips** [hlissner/.emacs.d#182]
So this is weird. On Archlinux, I installed Fira Sans and Fira mono from pacman. Gnome terminal displays Fira sans perfectly and when I launch emacs - after it loads - I can set Fira Sans within emacs from the font menu, but on launch and with make doctor the font is not found. 

I've tried a lot of different tweaks, but haven't found a solution. Any thoughts on what to try?

**Comment by rphillips** [comment]
So it seems like the font is used now, but make doctor still doesn't find it.

**Comment by hlissner** [comment]
Odd, I'm using Arch as well and don't get this issue. 

What package did you install the fonts from? `community/ttf-fira-mono` and `community/ttf-fira-sans`? And 

Also, could you share the output of `fc-list | grep -i fira`?

**Comment by rphillips** [comment]
I reinstalled and things cleared up, so I can't easily test again. I did install the fonts from those locations, and fc-list did show the fonts. We can close the issue if you like. If I see the issue again, I'll post back with more debug info.

**Comment by hlissner** [comment]
Very strange. Perhaps it was a font cache issue? In either case I'll close this for now. Reopen if you come across the proble magain.
