### ISSUE TITLE
Warning on startup 'lexical variable'

### ISSUE THREAD

**Issue by thequantumcat** [hlissner/.emacs.d#184]
In the latest version of DOOM/emacs, I get the following warning on startup:

Warning (bytecomp): Unused lexical variable ‘faces’
Warning (bytecomp): Unused lexical variable ‘active’

Also, the modeline on the dashboard doesn't have the same color as it did before reinstalling DOOM/emacs.  However, the `make doctor` tool doesn't show errors.

**Comment by hlissner** [comment]
I believe this has been addressed on the `develop` branch. I'll be merging this into master over the weekend.
