### ISSUE TITLE
Org-capture adds hooks to non-org files

### ISSUE THREAD

**Issue by russmatney** [hlissner/.emacs.d#186]
Hit a bug editing in elixir this week: if I use `org-capture` in a file, some undesirable org-specific hooks are added. Specifically, editing:

```
0.99999
|> Float.round(3)
```

results in:

```
0.99999
| > Float.round(23) |
```

because of [this evil-insert-state-exit-hook](https://github.com/hlissner/.emacs.d/blob/master/modules/org/org/config.el#L80).

Perhaps [realign-table-maybe](https://github.com/hlissner/.emacs.d/blob/master/modules/org/org/autoload/org.el#L15) should check if the file is an org one? Or org-capture shouldn't apply org-hooks to the current buffer (as opposed to just the capture buffer itself)?

I'm happy to take a shot at a fix, but thought i'd create the issue to see which direction makes more sense.

Doom is incredible! Thanks so much!

**Comment by hlissner** [comment]
Yikes, what an obvious blunder! I attached those buffer-local hooks on org-load-hook, rather than org-mode-hook.

In any case, the problem has been fixed. Those hooks should only apply to org-mode buffers. Feel free to reopen this if that isn't the case.

**Comment by russmatney** [comment]
works great, thanks for the fix!
