### ISSUE TITLE
Error (doom-post-init-hook): void-function in ’doom|init-ui’ -> Symbol’s function definition is void: doom-themes-org-config

### ISSUE THREAD

**Issue by Ptival** [hlissner/.emacs.d#189]
I get this error after launching emacs. Any idea what might happening, or anything I can do to help debug this?

**Comment by amoriello** [comment]
Hum, did you run make update?

**Comment by Ptival** [comment]
Heh, yeah, sorry, that solved it. What is the sequence of commands one should follow to ensure everything is updated?

**Comment by hlissner** [comment]
Simply run `make` after you update. I'd also suggest you recompile, if you've byte compiled: `make recompile`
