### ISSUE TITLE
[TAB] Broken in magit?

### ISSUE THREAD

**Issue by knubie** [hlissner/.emacs.d#19]
First of all, what an awesome configuration you've got here! This repo finally convinced me to make the jump from vim to emacs and I'm very impressed so far.

Now, on to the issue. After playing with magit a bit, I realize that `TAB` to toggle the diff of a file wasn't working. So I did `F1 k [TAB]` to see what it was mapped to, and it's mapped to `doom/evil-matchit`. Removing that binding allows magit to work correctly, in that regard. Is there a different, preferred key for that functionality in your set up?

**Comment by hlissner** [comment]
Thank you! And I apologize for getting to this so late. After the holidays I'll push a fix to simply unbind the key in magit buffers. I'll let you know once I have!

**Comment by rjww** [comment]
Seems to cause issues in Org mode buffers too. I ran into it when trying to `TAB`-complete a new row in an Org table.

Thanks from me, too, for making your config available. Although in a very real way, thanks for nothing, because now I've well and truly fallen down the rabbit hole of meticulously picking through it.

**Comment by hlissner** [comment]
Alright, the Tab key in magit and org-mode buffers should be fixed. Let me know if it hasn't.

@rjww Hahaha, I'm so sorry. I know exactly how deep that rabbit hole goes. Anyhow, I've restored Tab for navigating tables in org-mode (I prefer that myself as well).

**Comment by rjww** [comment]
Good, because it feels kind of weird raising an issue with an idiosyncrasy in someone else's Emacs config. ("Hey, I don't like that you set your config up so that this happens. Change please.")

**Comment by mattsawyer77** [comment]
Hello @hlissner, I'm wondering if this issue is back (or perhaps a similar one has cropped up). I'm on your develop branch, and have noticed an odd behavior in the last few weeks(?) where pressing the tab key on a line in the magit window sometimes doesn't expand the diff, until you move around and try to expand various other file diffs, and then it kinda starts working again. Should I open a new issue for this?

**Comment by mracos** [comment]
When I move the cursor using `j k` in the magit status buffer almost the same weird behavior [0] that @mattsawyer77 said happens. When I move the cursor using arrows keys it behaves correctly.
I'm not sure what is causing this behavior.

[0] The weird behavior is that it expands the wrong diff when I move using `j k` and press TAB.

<details>
<summary> Moving using the `j k` keys </summary>
<img src="https://user-images.githubusercontent.com/14015177/55106772-83f65000-50ae-11e9-9de2-efb232831480.gif" />

</details>

<details>
<summary> Moving using the arrows keys </summary>
<img src="https://user-images.githubusercontent.com/14015177/55106700-59a49280-50ae-11e9-9e53-ce2056db68e2.gif" />
</details>

### System information

<details>
<summary>Click to expand</summary>

- OS: darwin (x86_64-apple-darwin18.0.0)
- Emacs: 26.1 (Oct 04, 2018)
- Doom: 2.0.9 (develop ab616cfb95a19ebb68590e414ae0c1c5734690be)
- Graphic display: t (daemon: t)
- System features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES THREADS LCMS2
- Details:
  ```elisp
  elc count: 0
  uname -a:  Darwin ptreco.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64
  modules:   (:feature debugger eval (evil +everywhere +commands) file-templates (lookup +docsets) snippets workspaces :completion company (helm +fuzzy) :ui deft doom evil-goggles fci hl-todo modeline nav-flash treemacs (popup +all +defaults) pretty-code unicode vc-gutter vi-tilde-fringe window-select :editor fold (format +onsave) multiple-cursors parinfer :emacs dired imenu term vc :tools editorconfig flycheck flyspell macos magit pdf rgb terraform :lang data erlang elixir emacs-lisp javascript latex markdown (org +attach +babel +capture +export +present) php ruby (sh +fish) web :app write :config default)
  packages:  (persistent-scratch pinentry atomic-chrome wakatime-mode ob-mermaid (buffer-expose :recipe (buffer-expose :fetcher github :repo clemera/buffer-expose)) darkroom)
  exec-path: (/usr/local/bin/ /usr/bin/ /bin/ /usr/sbin/ /sbin/ /Library/TeX/texbin/ /usr/local/Cellar/git/2.21.0/libexec/git-core/ ~/.asdf/shims/ ~/.asdf/bin/ ~/.aliases.d/shims/ ~/bin/ /usr/local/sbin/ ~/.emacs.d/bin/ ~/.antigen/bundles/robbyrussell/oh-my-zsh/lib/ ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/asdf/ ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/bundler/ ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/docker/ ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/docker-compose/ ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/emacs/ ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/fzf/ ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git/ ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git-extras/ ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/last-working-dir/ ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/mix/ ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/osx/ ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/rake/ ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/scw/ ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/sudo/ ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/terraform/ ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/yarn/ ~/.antigen/bundles/chrissicool/zsh-256color/ ~/.antigen/bundles/hlissner/zsh-autopair/ ~/.antigen/bundles/marzocchi/zsh-notify/ ~/.antigen/bundles/willghatch/zsh-saneopt/ ~/.antigen/bundles/zdharma/fast-syntax-highlighting/ ~/.antigen/bundles/zsh-users/zsh-autosuggestions/ ~/.antigen/bundles/zsh-users/zsh-completions/ ~/.antigen/bundles/Tarrasch/zsh-bd/ ~/.antigen/bundles/agkozak/zsh-z/ ~/.antigen/bundles/gusaiani/elixir-oh-my-zsh/ ~/.antigen/bundles/sobolevn/wakatime-zsh-plugin/ ~/.antigen/bundles/supercrabtree/k/ ~/.antigen/bundles/zdharma/zsh-diff-so-fancy/ ~/.antigen/bundles/andrewferrier/fzf-z/ ~/.antigen/bundles/mafredri/zsh-async/ ~/.antigen/bundles/Dfurnes/purer/ ~/.antigen/bundles/zdharma/zsh-diff-so-fancy/bin/ /usr/local/Cellar/emacs-plus/26.1/libexec/emacs/26.1/x86_64-apple-darwin18.0.0/)
  ```
</details>

(Should I open a new issue for this @hlissner?)

**Comment by bittopaz** [comment]
@mracos can you check if you enable the visual line mode? I met the similar problem when enabled visual line mode. And after disable visual line mode, the issue is gone.

**Comment by mattsawyer77** [comment]
@bittopaz thanks, that’s a good workaround. I had almost stopped using magit due to this issue.

**Comment by bittopaz** [comment]
@mattsawyer77 glad it's helpful, it took me about two weeks to realize that it could be the problem...

**Comment by mracos** [comment]
So much thanks @bittopaz, disabling `visual-line-mode` made the TAB in magit buffer work as expected again!

**Comment by mattsawyer77** [comment]
Maybe this will help someone else. I changed 
```elisp
(global-visual-line-mode 1)
```
to
```elisp
(add-hook 'prog-mode-hook 'turn-on-visual-line-mode)
```
(or could use `'text-mode-hook`). Anyway, sorry for the noise on this issue, as it's clearly unrelated to doom-emacs. :/

**Comment by siawyoung** [comment]
Thank you @mattsawyer77 - this issue was driving me crazy and I couldn't figure out what was happening.
