### ISSUE TITLE
Updating packages from a non-standard directory

### ISSUE THREAD

**Issue by UndeadKernel** [hlissner/.emacs.d#190]
If emacs doom is located in a directory other than "/home/user/.emacs.d", running `make update` fails with the message:

> Cannot open load file: No such file or directory, /home/user/.emacs.d/core/core-packages

**Comment by hlissner** [comment]
This should be fixed in the latest commit. Let me know if it isn't.

Sidenote: byte-compiling doom, _then_ moving it before running `make update` can cause this issue too, in that case, you need to recompile or get rid of *.elc files altogether (`make clean`).

**Comment by UndeadKernel** [comment]
This was a tricky bug that you spotted immediately.
Your lisp-foo is strong with you.

Thank you for your work.
