### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by aminroosta** [hlissner/.emacs.d#2]
Make command fails with the following error.

```
Wrote /var/folders/sv/yzk7g2ld3y5_qjxnk_36bj880000gn/T/cask/packages/counsel-css-20160604.2144.el
Dependency counsel-css failed to install: End of file during parsing: /usr/local/Cellar/cask/0.7.4/cask-cli.el
Output:
Saving file /var/folders/sv/yzk7g2ld3y5_qjxnk_36bj880000gn/T/cask/packages/counsel-css-20160604.2144.el...

make: *** [_install] Error 255
```

**Comment by hlissner** [comment]
I know the problem. It's an odd issue that occurs when Cask tries to install [counsel-css](https://github.com/hlissner/emacs-counsel-css) that I haven't figured out yet. The workaround is to comment out `(depends-on "counsel-css" :git "https://github.com/hlissner/emacs-counsel-css")` in the `Cask` file. It should be on line 168.

I'll figure out a fix for this soon.

**Comment by hlissner** [comment]
Sorry, seems I forgot about this issue! It should be fixed by now, so I will close it.
