### ISSUE TITLE
[QUESTION] will u add which-key support?

### ISSUE THREAD

**Issue by babygau** [hlissner/.emacs.d#23]
hi,

i run into your emacs config and immediately feel impressive with how organised your emacs is. it's inspirational. however im using spacemacs  and love `SPC` key too much to leave it, even though spacemacs feel bloated with many unused packages and slow. i'm wondering if you could add which-key  support in have it baked in  your `map!` macro so that i could customised the keybindings based on spacemacs for example  from [here](https://sam217pa.github.io/2016/09/02/how-to-build-your-own-spacemacs/)

tks again.

**Comment by hlissner** [comment]
Hi! And thank you, I'm glad you like it.

I'd be happy to include which-key support. Even I forget my own keybindings sometimes.

I am currently working on v2 of my emacs config (a huge rewrite; yes, I might be a _little_ insane), which should be done within the week. Afterwards I will look at integrating which-key.

**Comment by babygau** [comment]
awesome, that's great news, and i do hope that your new version would be written much better than current one and of course easier to understand and follow for one would like to customise it . keeping up your your amazing work 👍

**Comment by hlissner** [comment]
v2 incorporates which-key support (though, only for the leader and localleader keys -- `,` and `\` by default). This can be expanded in `core/core-keybinds.el`, but I'm happy where it is for now, so I'll close this issue.
