### ISSUE TITLE
Error message while switching projects 

### ISSUE THREAD

**Issue by mrmansano** [hlissner/.emacs.d#25]
Hello,

first of all, THANK YOU VERY MUCH for your work, your .emacs.d is one of the bests I have ever seen and I'm already using it (with minor modifications) as my main emacs configuration.  

Now, I'm having some problems while doing the 'projectile-switch-project' command. In fact, the project is switched to the selected one, but when the *scratch* buffer is being openned the message below pops into the *Messages* buffer.

`doom/wg-projectile-switch-project: Symbol’s function definition is void: doom-reload-scratch-buffer`

For my setup, I commented the line 16 at core/defuns/defuns-workgroup.el, and that solved the problem for me.

**Comment by hlissner** [comment]
Sorry for the late reply!

> first of all, THANK YOU VERY MUCH for your work, your .emacs.d is one of the bests I have ever seen and I'm already using it (with minor modifications) as my main emacs configuration.

Thank you! And you're very welcome.

> Symbol’s function definition is void: doom-reload-scratch-buffer

The correct function name is `doom-scratch-reload`. If you correct that on the line you commented out, it should work fine. I renamed it a while back and forgot to update defuns-workgroup.el, my bad!

I'm doing a huge rewrite of my config at the moment (should be done this weekend), so I may not push a fix for the current version.

**Comment by hlissner** [comment]
I'll close this issue since it's resolved in v2, which I've just merged to master.
