### ISSUE TITLE
doom*delete-popup-window: Is the nesting correct here?

### ISSUE THREAD

**Issue by rjww** [hlissner/.emacs.d#27]
[Line 179 of `core-popups.el`](https://github.com/hlissner/.emacs.d/blob/bf691bec14426c4df5ac4207e28c3b73de5f60bf/core/core-popups.el#L179) is indented as if it's meant to be nested within the previous `unless` condition, but the parens put it outside this. Might want to check if it's correct as is, or a syntax error.

**Comment by hlissner** [comment]
Good catch. It is indeed an indentation error; it's in the right place, but indented incorrectly. It'll be fixed in a moment.

**Comment by hlissner** [comment]
And done. Thanks for reporting that!
