### ISSUE TITLE
Not sure Org capture is working as it's supposed to in v2

### ISSUE THREAD

**Issue by rjww** [hlissner/.emacs.d#28]
The popup frame created by `+org/capture` just seems to display the current buffer, and the `:org` ex command raises an error: `evil-ex-call-command: Cannot open load file: No such file or directory, emacs/org/autoload/evil`.

**Comment by hlissner** [comment]
Aye, the org module needs a revisit. That particular error is caused because the autoload cookies are out of date. Thanks!

**Comment by hlissner** [comment]
Needs a little more testing, but this was fixed in #a446c58
