### ISSUE TITLE
Overriding individual popup settings

### ISSUE THREAD

**Issue by rjww** [hlissner/.emacs.d#29]
Would it be possible to implement some way of overriding elements in `shackle-rules` created with `(set! :popup)`? For context, I'm looking to make the popup for Org agenda buffers larger.

It'd be easy to just edit the relevant rule in the base config, but rather than hacking on that, I'm trying to implement my own config entirely through `modules/private`, so that I don't actually have to fork the repo. Obviously not a huge priority, but any help would be much appreciated. (And if there's already a good way of doing this that I've overlooked, please let me know!)

**Comment by hlissner** [comment]
Yes it is. You can simply use `(set! :popup ...)` again. Newer settings will overshadow old ones.

**Comment by rjww** [comment]
Not sure what I'm doing wrong. Maybe it's got something to do with the order in which the rule is being prepended.

I've got a config file in `modules/private/rjww` that's loaded by `config.el`. In that, I've tried just `(set! :popup "^\\*Org Agenda" :regexp t :size 0.6)`, as well as nesting that in `(add-hook! org-load ...)` and `(after! org ...)`.

**Comment by hlissner** [comment]
Ah, yes it is the order. The org popup hacks are _prepended_ to org-load-hook, and `add-hook!` prepends to hooks as well. That means anything any hooks you add later will get run before the defaults, which shadow your custom ones.

I've applied to load those popup hacks as late as possible. If you nest that `set!` in an `(add-hook! org-load ...)` it should work now.

**Comment by rjww** [comment]
That's great, thanks so much for your help.

**Comment by rjww** [comment]
Whoops, looks like the change might have interfered with something else. The agenda now appears in a popup frame, and the modeline is visible.

**Comment by hlissner** [comment]
That's odd. Are you running emacs with the `-q` flag, per chance (or with `make run`)? Emacs doesn't run `after-init-hook` and `window-setup-hook` with the `-q` flag, which would prevent the defaults from being initialized at all.

**Comment by rjww** [comment]
I tried running `make clean`, deleting my `.local` directory, and reinstalling and recompiling everything. Now the popup is appearing as it should, but the modeline is still there. I just tried starting with your `:private` setup instead, and it's fine, so clearly it's something in mine. I'll poke around and figure out what I've done. Thanks again for your help!
