### ISSUE TITLE
Missing 'doom-one' after fresh install

### ISSUE THREAD

**Issue by DonHansDampf** [hlissner/.emacs.d#3]
Followed your installation process and got some errors while the 'make'-process. The package "emacs-eclim" caused some problems. After commenting the java-modules out of the cask file, the make-command run without an error. 

Still i cant start emacs, since i get an error about the missing theme 'dark-one'. And it seems like everything in the init.el depends on it. Am i missing something?

**Comment by hlissner** [comment]
Ah yes, these two things are fixed in the dev branch. I will be merging it into master within the next hour or two.

**Comment by hlissner** [comment]
And done! Let me know if that helped.

**Comment by DonHansDampf** [comment]
Yep, it now works without a problem. Also 'emacs-eclim' complies. Thanks a lot!
