### ISSUE TITLE
Bundled version of Org-mode being used instead of latest from official repo

### ISSUE THREAD

**Issue by rjww** [hlissner/.emacs.d#36]
See [this issue on StackOverflow](http://stackoverflow.com/questions/31855904/emacs-sees-the-directory-with-the-new-org-mode-version-but-loads-the-old-versio).

**Comment by hlissner** [comment]
I'd forgotten about it, but it's fixed now. After the latest commit `org-version` shows 9.0.5. Feel free to reopen this if the problem persists.
