### ISSUE TITLE
[v2] loading

### ISSUE THREAD

**Issue by karetsu** [hlissner/.emacs.d#39]
Hey there, currently trying out v2 having used v1 for a while and looking forward to the refactoring. I'm just encountering some strange behaviour with Haskell, python and a few other languages. When I open e.g. foo.js it loads the correct mode but it doesn't pick up the mode for .hs, .py, .go etc. Is this because its not meant to work yet? 

I've done nothing but pull the latest version of v2, cp init.el and run make - it is the 'vanilla Lissner' edition.

Not sure if this is really an issue or just a question so feel free to close if its not meant to function yet.

**Comment by hlissner** [comment]
Haskell and go have been neglected so they likely need more work, but I fixed them with the latest commit, but I couldn't find anything wrong with python (i've used it considerably in the past couple of weeks). Do you get any error messages in `view-echo-messages-area`?

**Comment by karetsu** [comment]
Ah, just did a power cycle and a python file worked 'fine'. Only seems to offer 2.7.10 when 3.6.0 is the default interpreter but I can deal with that. We can remove python from the problem. 

`view-echo-messages-area' only complains about
Warning: arch-dependent data dir '/Users/build/workspace/Emacs-Multi-Build/label/mavericks/emacs-source/nextstep/Emacs.app/Contents/MacOS/libexec/': No such file or directory


You can close this as a non-problem if hs and go are pending, thanks :)

**Comment by hlissner** [comment]
@karetsu Just a hunch, but try running `M-x eval-expression RET (executable-find "python")` and see if it finds the correct python. Chances are your `exec-path` isn't populated properly, and that means there's a bug in core/core-os.el.

**Comment by garethclews** [comment]
I'll have to take a look when I get home from work, thanks

**Comment by karetsu** [comment]
Nope, its just started working - python 3 in the repl [document mode still says 2.7.10 but that's thankfully really only aesthetics]. Not a problem :)

**Comment by karetsu** [comment]
`M-x eval-expression RET (getenv "PATH")` 
"/usr/bin:/bin:/usr/sbin:/sbin:/foo/bar/mac/emacs/location"

This is a very different path to what I actually have set. Its preventing cabal from finding ghc [which is in /usr/local/bin] for one so dante falls on its face. Could this be why I'm seeing py2?

**Comment by hlissner** [comment]
This is a known problem with GUI Emacs on macos (it runs in its own isolated environment), but if you're using my emacs.d it isn't a problem (I use the `exec-path-from-shell` plugin, which fixes the issue).

You see, Emacs uses the `exec-path` variable as the PATH for shell commands within Emacs.

So to see if there _is_ a problem, run `M-: (executable-find "python")` (does it resolve to the correct binary?) and `M-: (shell-command-as-string "echo $PATH")` (does it produce the correct PATH?).

**Comment by karetsu** [comment]
Running as a standard Mac app (isolated) I have
![isolated](https://cloud.githubusercontent.com/assets/20670199/24071678/d9b3fa9a-0bcf-11e7-871a-dc8070201f84.png)
Doing the exact same thing but opening it via zsh:
![term-py](https://cloud.githubusercontent.com/assets/20670199/24071676/d9b395c8-0bcf-11e7-91a7-fb58f4728cf6.png)

I don't like that there is a difference, but python works fine other than what the images show and its not really a thing outside of being anal about versions.

Haskell however, is an issue. Isolated mac app opening and then just doing `C-x C-f tmp.hs` I'm greeted with:
![isolated_dante](https://cloud.githubusercontent.com/assets/20670199/24071677/d9b3aab8-0bcf-11e7-9d82-8b4f5c057c85.png)
but `M-: (executable-find "ghc")` gives the correct one. This does not happen when a haskell file is loaded via [insert shell of choice] - it just seems far more awkward to get a REPL and the best way I have is to `:vsplit`, `C-w l`, `:interactive-haskell-mode` then go back and use `C-c C-l` and then its fine.

**Comment by karetsu** [comment]
Nothing to be done - MacOS issue
