### ISSUE TITLE
How do you open magit?

### ISSUE THREAD

**Issue by saulius** [hlissner/.emacs.d#4]
I get this error while trying to enable magit:

```
uniquify-rationalize-file-buffer-names: Wrong type argument: stringp, (" \\*doom\\*")
```

Any ideas how to fix this?

Thanks!

**Comment by saulius** [comment]
Looks good, thanks!

**Comment by hlissner** [comment]
No prob! Thanks for reporting it. Turns out I misconfigured uniquify, causing it to throw errors when opening certain windows. Good to know the problem is gone!
