### ISSUE TITLE
emacs term support

### ISSUE THREAD

**Issue by amoriello** [hlissner/.emacs.d#40]
Hey! Such an awesome work done here!!

I wanted to try the built-in terminal emulator (M-x term) under your config, and I noticed some funny behaviour going on there. Looks like a mix of insert / emacs and evil-normal mode... HJKL do move the cursor around instead of inserting text, while other keys insert text as expected.

In core/core-evil.el, I see `evil-set-initial-state` to 'emacs' for term-mode, though.

Please, let me know if I missed something.

Thanks again for this amazing work, I got inspired to write and organise my own configuration the same way.

-----
### Version info
emacs: GNU Emacs 25.2.2
shell: zsh 5.3.1 (x86_64-apple-darwin16.3.0)  -- but I also observe similar symptoms with bash
.emacs.doom@e8438e1

### Steps to reproduce:
- (M-x term)
- HJKL move the cursor around instead of inserting text.

**Comment by hlissner** [comment]
Thanks! And good catch. I have [hjkl bindings in private/my-bindings.el](https://github.com/hlissner/.emacs.d/blob/master/private/my-bindings.el#L51) for the emacs state. Remove those and you should be golden!

**Comment by amoriello** [comment]
Ok! Out of curiosity... why would you override HJKL in emacs mode?

**Comment by hlissner** [comment]
To be honest, I've forgotten, haha. Likely one of the org-mode agenda buffers whose vanilla emacs bindings I didn't want to compromise by using normal mode, so I bound the familiar hjkl keys, forgetting that I'd affect every other buffer in emacs mode!

Whatever it was, those bindings are gone in [my v2 rewrite](https://github.com/hlissner/.emacs.d/tree/v2).

**Comment by hlissner** [comment]
I'm assuming that my suggest fixed the issue, so I'll close this. Feel free to reopen if that isn't the case.
