### ISSUE TITLE
Haskell not getting interactive mode

### ISSUE THREAD

**Issue by karetsu** [hlissner/.emacs.d#42]
When loading haskell mode it doesn't appear to pull in any minor mode. Every time I hit `C-c C-l` after Dante starts GHCi I get a _look in the help to see how to set up a Haskell interactive mode_ kind of error.

This has a one line fix (I'm not at my computer now to submit a pull request). Change the final block of modules/lang/haskell/config.el to:

    (def-package! dante
      :after haskell-mode
      :config
      (when (executable-find "cabal")
        (add-hook! 'haskell-mode-hook '(flycheck-mode dante-mode)))
        (add-hook 'haskell-mode-hook 'interactive-haskell-mode))

fixes it [although it may not be the best place to put it?]. Unless I'm the only one actually having this problem, in which case just close it down.

**Comment by hlissner** [comment]
Ah, I forgot to add that hook. I added it. Though, the haskell module still needs some TLC. I won't be using haskell for a while, so I'm open to suggestions!

**Comment by karetsu** [comment]
Then I will fork and have a look :)
