### ISSUE TITLE
Just a typo

### ISSUE THREAD

**Issue by sirikid** [hlissner/.emacs.d#43]
Hello Henrik!
During the reading I found a small typo - [here][line] (`filse` instead of `files`).
Thanks for this repository, it's very inspiring.

[line]: https://github.com/hlissner/.emacs.d/blob/master/core/core.el#L41

**Comment by hlissner** [comment]
Whoops! Haha. Good catch, but I'm currently focused on [the v2 branch of my config](https://github.com/hlissner/.emacs.d/tree/v2), which I'll merge into master soon (and doesn't have the typo!), so I won't be fixing anything in master until then. Thanks though!

**Comment by sirikid** [comment]
Wow, v2 looks sweet, I'll wait for release.
