### ISSUE TITLE
Indentation "jitter" with plain lists in Org mode

### ISSUE THREAD

**Issue by rjww** [hlissner/.emacs.d#44]
Not sure the best way to describe this, but when typing into an item in a [plain list](http://orgmode.org/manual/Plain-lists.html) in Org mode, the list item will "jitter", or jump between being indented and not indented. Presumably this has something to do with electric indentation or `org-indent-mode`?

**Comment by hlissner** [comment]
`org-indent-mode` is likely at fault, since `electric-indent-mode` is disabled in org-mode. Could you provide a test case though? I haven't been able to reproduce this.

**Comment by rjww** [comment]
I just updated `railwaycat-emacs` and pulled the latest commits from the repo, and it's looking fine at the moment. I'll close this for now, and let you know if it crops up again!
