### ISSUE TITLE
TAB hijacked in Org mode tables

### ISSUE THREAD

**Issue by rjww** [hlissner/.emacs.d#45]
I think this is just a reemergence of #19 in [v2](https://github.com/hlissner/.emacs.d/tree/v2).

**Comment by hlissner** [comment]
Just a hunch, but does this occur while you're in normal mode? If so, that is intended. I've only bound `tab` to `'+org/indent-or-next-field` in insert mode (if I'm in normal mode, I consider other motions for getting around).

Though, I suppose i could make a `+org/tab-dwim` command that will use matchit, indent or navigate tables depending on context...

**Comment by rjww** [comment]
No, unfortunately it's in the insert state too.

**Comment by rjww** [comment]
Should have mentioned that `Shift-TAB` works fine for going backwards.

**Comment by hlissner** [comment]
Could you remind me what OS you're using? If chances are that binding only to `[tab]` won't work, and I'll need to bind it to (kbd "TAB") too.

**Comment by hlissner** [comment]
Turned out yasnippet was hijacking TAB in org-mode. I've fixed it in the latest commit. Let me know if you still have the problem.

**Comment by rjww** [comment]
Sorry for being slow to reply, I've been sick. Checking out the newly merged master branch now, so I'll let you know if the problem comes up again.
