### ISSUE TITLE
Tab emulation config ?

### ISSUE THREAD

**Issue by ragloo** [hlissner/.emacs.d#46]
Great config and theme.
I'm sorry but I was not able to find in your config the tab emulation part.
Where can I look ?
Thanks

**Comment by hlissner** [comment]
In v1.3, it's in [core/core-workgroups.el](https://github.com/hlissner/.emacs.d/blob/master/core/core-workgroups.el).

However, I suggest you look at v2.0's implementation in [modules/feature/workspaces](https://github.com/hlissner/.emacs.d/tree/v2/modules/feature/workspaces), which is more stable and (I think) easier to understand.

There are also keybindings spread across [modules/private/hlissner/+bindings.el](). Here's are the most pertinent ones:

```
 ;; Switching tabs (workspaces)
 "M-1"  (λ! (+workspace/switch-to 0))
 "M-2"  (λ! (+workspace/switch-to 1))
 "M-3"  (λ! (+workspace/switch-to 2))
 "M-4"  (λ! (+workspace/switch-to 3))
 "M-5"  (λ! (+workspace/switch-to 4))
 "M-6"  (λ! (+workspace/switch-to 5))
 "M-7"  (λ! (+workspace/switch-to 6))
 "M-8"  (λ! (+workspace/switch-to 7))
 "M-9"  (λ! (+workspace/switch-to 8))
 "M-0" '+workspace/switch-to-last

 ;; Simple window navigation/manipulation
 "M-t"    '+workspace/new
 "M-T"    '+workspace/display
```

(note: `(λ! ...)` is simply a macro for `(lambda () (interactive) ...)`)

I hope that helps, and feel free to ask if you have other questions.

**Comment by hlissner** [comment]
Also, I'm not sure if you're an evil user, or if vim-tab parity is important to you, but you'll also find some ex commands in [modules/private/hlissner/+commands.el](https://github.com/hlissner/.emacs.d/blob/v2/modules/private/hlissner/%2Bcommands.el):

```elisp
(defalias 'ex! 'evil-ex-define-cmd)

(ex! "tabc[lose]"  '+workspace:delete)
(ex! "tabclear"    'doom/kill-all-buffers)
(ex! "tabl[ast]"   '+workspace/switch-to-last)
(ex! "tabload"     '+workspace:load)
(ex! "tabn[ew]"    '+workspace:new)
(ex! "tabn[ext]"   '+workspace:switch-next)
(ex! "tabp[rev]"   '+workspace:switch-previous)
(ex! "tabr[ename]" '+workspace:rename)
(ex! "tabs" '+workspace/display)
```

And some evil-esque keybindings from [modules/private/hlissner/+bindings.el](https://github.com/hlissner/.emacs.d/blob/v2/modules/private/hlissner/%2Bbindings.el)

```elisp
 ;; Switch tabs
 :n  "]w" '+workspace/switch-right
 :n  "[w" '+workspace/switch-left
 :m  "gt" '+workspace/switch-right
 :m  "gT" '+workspace/switch-left
```

and these remappings:

```elisp
 (define-key persp-mode-map [remap delete-window] '+workspace/close-window-or-workspace)
 (define-key persp-mode-map [remap evil-window-delete] '+workspace/close-window-or-workspace)
```

**Comment by ragloo** [comment]
Waouuuh, many thanks !
Love your doom-themes also a lot !

Many thanks and excellent work :)

**Comment by hlissner** [comment]
I personally believe it _is_ a good replacement. However, the two work a little differently. Tabbar gives you tabs for each **window**. My persp-mode implementation gives you tabs for each **frame**.

The former isn't very useful to me because i prefer the likes of `persp-switch-to-buffer` empowered with `ivy-mode`. They make switching to other buffers easier. I've also customized `persp-switch-to-buffer` to show more information about each buffer (modified state, major mode, project, etc).

In the end, it's up to you though. I know a few people who seem to use my emacs.d with tabbar.
