### ISSUE TITLE
fatal: destination path 

### ISSUE THREAD

**Issue by 4goodapp** [hlissner/.emacs.d#47]
Got this error while trying to install on ubuntu 16.04
git clone https://github.com/hlissner/.emacs.d ~/.emacs.d
fatal: destination path '/home/mywork/.emacs.d' already exists and is not an empty directory.

**Comment by karetsu** [comment]
This is because you already have an Emacs configuration.

`mv ~/.emacs.d ~/.o.emacs.d && git clone [the rest...]`

**Comment by hlissner** [comment]
@karetsu is correct. Either move the original folder (as he suggested) or delete it (`rm -rf ~/.emacs.d`) before you try my instructions.
