### ISSUE TITLE
Readme points to the wrong file for modeline stuff

### ISSUE THREAD

**Issue by deontologician** [hlissner/.emacs.d#5]
I guess you moved it over to https://github.com/hlissner/.emacs.d/blob/master/core/core-modeline.el, the readme points to the core-ui file

**Comment by hlissner** [comment]
I'm confused. Where do you see a core-ui link in the readme? There should be a link to my modeline file in either case though. I will add it.

**Comment by hlissner** [comment]
I updated the readme a while ago, so I'll consider this fixed.
