### ISSUE TITLE
weird indentation problem

### ISSUE THREAD

**Issue by vsr625** [hlissner/.emacs.d#50]
I noticed a small mistake in your private/bindings.el
 ;; Temporary escape into emacs mode
 [C-escape]    'evil-emacs-state
 :n [C-escape] 'evil-normal-state

shouldn't this be like  :e [C-escape] 'evil-normal-state, so as to go back to evil mode from emacs state.

The indentation is acting sort of weird, if I manually press TAB then the indention would contain 4 spaces, and if I select say snippets, the indentation would contain 2 spaces, and if I manually open braces, the braces would autamatically get aligned to four spaces, and after opening braces, if press enter, the cursor gets placed inside braces with 2 spaces for indentation.

I'm only trying this in c++ mode, as I only edit cpp files.
Can you please help me with this, btw this is like the best emacs config that I ever found, it loads up very fast, and it looks sick as heck, everything is functional, and I like the way you laid out the map function, it is now super easy to add bindings to anything actually. Thanks

**Comment by hlissner** [comment]
> Re: [C-escape]
Good catch! That is definitely a mistake.

> Re: weird indentation
That does sound weird. Could you provide specific steps for reproducing the issue?

> Thanks
Thank you! And you are very welcome!

**Comment by vsr625** [comment]
If there is no text, and if press tab, it would contain four spaces.
Although is would contain four spaces initially, if I type a statement and end it with a semicolon, it would the indentation in the beginning would go back to 2 spaces. Example:

|             // Initial position
    |         // After pressing tab
    int x|   // No changes
  int x;|    // After completing the statement i.e. ending with semicolon

I mean this shouldn't happen right?

**Comment by vsr625** [comment]
Sorry to bother you, but this solution fixed it for me.
http://stackoverflow.com/a/663636
Now everything gets indented perfectly as expected.
Is there anyway to set the  c-basic-offset value based on the current tab spaces used, it would remove redundancy to update two places if one wished to change the spaces for tab.

And why aren't the suggestions for autocomplete not showed, I mean, like the list of suggestions for completions, is supposed to be this way?

**Comment by hlissner** [comment]
Ah, I understand what's going on. My config relies on [editorconfig](http://editorconfig.org/) to configure per-project whitespace settings (like tab widths, as well as C/C++ indent offsets). You have to have either a) a global [~/.editorconfig](https://github.com/hlissner/dotfiles/blob/master/editor/%2Beditorconfig/.editorconfig) file or b) an `.editorconfig` file in your project for my config to read these settings from.

Without this, it resorts to the default (2 spaces) which causes your problem.

So here are two choices to fix this:

+ `(setq-default c-basic-offset tab-width)` (which I will add to my config soon)
+ or create a global config. [This is mine.]((https://github.com/hlissner/dotfiles/blob/master/editor/%2Beditorconfig/.editorconfig))

> Is there anyway to set the c-basic-offset value based on the current tab spaces used

I would suggest looking into [editorconfig](http://editorconfig.org/), as mentioned above.

> And why aren't the suggestions for autocomplete not showed

Auto-completion requires irony-server to be installed. You install it with `M-x irony-install-server`. If you're on MacOS, you'll need libclang installed. Easiest way to get it is `brew install llvm`, but that installation will take a while.

**Comment by vsr625** [comment]
Thank you for taking the time to reply.
