### ISSUE TITLE
How do you work with checkboxes in Org mode?

### ISSUE THREAD

**Issue by gilbertw1** [hlissner/.emacs.d#57]
Hey, if you don't mind I've got a few quick questions about how you manage your checkboxes (like in TODO.org) in org mode. I really like the setup a lot, and I was wondering a few things:

1) How do you create sub-lists w/ counts (eg. [6/80]) on the org heading
2) What keybindings do you use to add new items to the sub lists
2) Do you have a keybinding for toggling the state of a checkbox

I've tried working with your TODO.org document or creating something similar on my own, but I just can't seem to figure out the keybindings to create / add to / and manipulate your sub lists (items with the ```+``` in front) effectively. Thanks in advance!

**Comment by apierz** [comment]
Adding '[/]' to the end of a heading  will add the count. It will dynamically update as the status of check boxes below updates. The default binding for check box status in org-mode is C-c C-c

**Comment by hlissner** [comment]
1. As apierz said, add `[/]` to the heading (or list item). I don't remember if it's automatic. I have this to make sure it is:

    ```emacs-lisp
    (defun +org|update-cookies ()
      "Update counts in headlines (aka \"cookies\")."
      (when (and buffer-file-name (file-exists-p buffer-file-name))
        (org-update-statistics-cookies t)))

    (add-hook 'before-save-hook #'+org|update-cookies nil t)
    (add-hook 'evil-insert-state-exit-hook #'+org|update-cookies nil t))
    ```

2. I've bound `M-RET` and `M-S-RET` for adding new list items

    ```
          :ni "<M-return>"   (λ! (+org/insert-item 'below))
          :ni "<S-M-return>" (λ! (+org/insert-item 'above))
    ```
    It also works with headings (when point is on a heading) and org table cells (I think, I've been working on this lately. If it isn't working now, it will soon).

3. Yes, just `RET` in normal mode, which is bound to `+org/dwim-at-point`, which is a bit of a monster. It'll do everything from switching TODO states on a headling, checking checkboxes, to toggling LaTeX previews and an inline image, to following links, etc.

**Comment by gilbertw1** [comment]
Perfect, thank you both!
