### ISSUE TITLE
How to set "jj" or "jk" as evil-normal-state?

### ISSUE THREAD

**Issue by rizafahmi** [hlissner/.emacs.d#58]
I can do using key-chord, but how to do that using this setup?

**Comment by hlissner** [comment]
I using `evil-escape` ([here](https://github.com/hlissner/.emacs.d/blob/master/modules/feature/evil/config.el#L270)). I've found it to be more responsive than key-chord. I only activate it in insert and replace mode, though I may extend it soon.

**Comment by rizafahmi** [comment]
Nice! I'm not aware that you already use "jk" as escape key. Thanks for your hard work. The configuration is awesome! 🎉
