### ISSUE TITLE
Periodically missing line numbers

### ISSUE THREAD

**Issue by gilbertw1** [hlissner/.emacs.d#59]
I'm noticing on occasion that some line numbers are missing in some of the buffers I'm working in. It looks like this:

![missing-line-numbers](http://drop.bryan.codes/i02H9YIz3d.png)

It doesn't seem to be specific to any any modes, although I do seem to notice that it happening more frequently on buffers that have been open for a while. Moving the cursor to the line does not fix the missing line number, however if I edit a line with a missing line number, the number re-appears. Additionally after moving the cursor from the line, all other lines that had a missing line number below it have their line number reappear as well.

Have you experienced this at all? Do you have any pointers on what a likely cause is? So far I haven't had any luck poking around to solve this issue.

Thanks!

**Comment by hlissner** [comment]
I have experienced this and do frequently, across several computers and OSes. My hunch is that it has to do with Emacs' garbage collection greedily "evaporating" jit overlays.

I've been considering a move back to `linum`. In my Emacs "career", nlinum has been more trouble than it was worth. If you prefer to stick to it, this is the bandaid solution I've lived with the past few months:

```emacs-lisp
  (defun doom*nlinum-flush (_ &optional norecord)
    (when (and nlinum-mode (not norecord))
      (nlinum--flush)))
  ;; refresh when switching windows
  (advice-add #'select-window :after #'doom*nlinum-flush)
  ;; when pressing esc in normal mode (if you're an evil user)
  (advice-add #'evil-force-normal-state :after #'nlinum--flush)
```

You could probably add `nlinum--flush` to other hooks, even `post-command-hook`, if you want to be really crazy (I imagine that'd completely eliminate any benefit of using nlinum over linum in the first place).

**Comment by gilbertw1** [comment]
Thanks for the tip! This goes a long way in relieving the (relatively minor) issue. I may look into moving to linum in the future, but this is good enough for now.

**Comment by hlissner** [comment]
Sorry to bring up an old issue, but a bout of hair-pulling later I've rediscovered why I switched to nlinum in the first place: linum-mode grinds Emacs to a crawl if you have the same buffer visible in more than one window. As I commonly use splits to edit two different places in the same file, that's quite imposing.

So I'm switching back to nlinum, plus some changes to help mitigate this issue, including a fix upstream to `doom-themes`'s nlinum integration, which will "repair" the current line number if it doesn't exist.

**Comment by gilbertw1** [comment]
Thanks for the heads up, I can live with a few line numbers missing occasionally, not so much with a laggy editor 👍 

Also, you've done a great job with the influx of new users, keep up the good work!

**Comment by hlissner** [comment]
I'm trying out a new fix that has worked flawlessly for me the past few days:

```emacs-lisp
(add-hook 'post-gc-hook #'nlinum-hl-flush-all-windows)
```

`nlinum-hl-flush-all-windows` comes from [nlinum-hl](https://github.com/hlissner/emacs-nlinum-hl), which is part of DOOM, but this post-gc-hook isn't yet.

Could you help me test it? I'm looking for performance (most likely caused by a `gc-cons-threshold` that's too high) or stability issues.

**Comment by gilbertw1** [comment]
Awesome! I'll test it and report back here after using it for a while.

**Comment by gilbertw1** [comment]
So, I've got some quick initial feedback. 

I haven't noticed any performance issues so far, however I did see some missing line numbers. I noticed that when I see them, I can wait (without peforming any other action that will flush line numbers) and they will resolve themselves after some period of time automatically (I'm assuming this is a gc run).

I removed the the ```select-window``` advice and the ```evil-esc``` hook and I started seeing missing line numbers very frequently. I noticed that they would resolve themselves on unpredictable intervals, which again I'm assuming is anytime the gc runs.

Were you expecting this hook to completely eradicate the missing line number problem or is it intended to be an additional opportunity to flush the line numbers and clean them up as frequently as possible?

**Comment by gilbertw1** [comment]
Also, I'll mention it happens incredibly frequently with ```play-routes-mode``` (https://github.com/brocode/play-routes-mode) for some reason. It makes it pretty easy to test with a fairly reliable source of missing line numbers.

**Comment by hlissner** [comment]
> Were you expecting this hook to completely eradicate the missing line number problem [...]

I was hoping! My bet was on an overzealous garbage collector, but either I'm wrong or the gc also runs independently of whatever triggers `post-gc-hook`. I guess this runs deeper.

> [...] it happens incredibly frequently with play-routes-mode [...]

Curious. Its footprint is tiny. That's a point against my gc theory.

**Comment by gilbertw1** [comment]
One potentially valuable piece of information:

If I see missing line numbers in a buffer, close emacs (perspectives autosave), reopen emacs (loading autosave), open the perspective I was in, then the exact same line numbers are still missing. This works consistently for me. Then if I "fix" the line number, by highlighting that line, it's consistently fixed when resuming the perspective.

I would expect if this were a GC issue then the behavior would likely be more random. I'll continue to try and observe more details about the appearance (or lack of appearance) of missing line numbers.

**Comment by gilbertw1** [comment]
The plot thickens:

It actually fails to render the EXACT same lines every time I load a perspective, regardless of whether or not I "fixed" that line. I thought that the 'fixed' line persisted when the perspective was saved, but it turns out that all the line numbers correctly render in the currently selected window when you open the perspective (and I left the cursor in that window when I closed emacs).

This indicates (at least I think it does) that the line number failing to render happens predictably based on identical factors. I also observed that the same line numbers no longer fail to render if I move the buffer even a single line and close + reload the perspective.

**Comment by gilbertw1** [comment]
Okay, so after a decent bit of debugging, I think I've found and fixed the source problem with the line numbers missing. It looks like in rare occasions when creating line numbers based on a region (using a range of characters), the while loop short circuits early based on an off-by-one condition. Essentially the loop should be inclusive of the upper limit of the range of characters provided to the ```nlinum--region``` function, but it is not and exits prematurely if the point is exactly equal to the upper bound, and does not add a line number for the last line within that region.

I've pushed a commit to bmacs where I override this function, correcting the condition in the while loop here: https://github.com/gilbertw1/bmacs/commit/d8dc39fbe41b60bc6109b782755b58a772e25788

Can you please add this function definition and turn off all nlinum flush hooks, and test that no missing line numbers exist?

Fingers crossed, this problem might be fixed for good :)

**Comment by gilbertw1** [comment]
Also, I've submitted this bug fix to the emacs mailing list.

**Comment by hlissner** [comment]
Fantastic work! I'll do that and let you know.

**Comment by hlissner** [comment]
So far things are looking good. I think this issue may be fixed, so i've added it to master.

**Comment by gilbertw1** [comment]
Looks like native line numbers might be coming the emacs:

https://lists.gnu.org/archive/html/emacs-devel/2017-06/msg00318.html

The post is a tad condescending, but a pretty exciting development none the less. Interestingly, he mentions in followup messages that he didn't include a direct comparison with nlinum because he considered it too slow to even compare given his test case.

Only downside is that he doesn't seem too excited about adding line number highlighting.

**Comment by hlissner** [comment]
I've followed it on and off for the past two weeks. Looks like he may change his mind on line number highlighting. In any case I look forward to native line numbers!

However, as far as this particular issue is concerned, I haven't seen any disappearing line numbers in the past month so I'll considered it resolved!

**Comment by gilbertw1** [comment]
Yep! from what I can tell, he's already given the current line a different face:

https://www.reddit.com/r/emacs/comments/6hux6a/native_display_of_line_numbers/dj2ilv2/
https://www.reddit.com/r/emacs/comments/6hux6a/native_display_of_line_numbers/djgq30b/

**Comment by gilbertw1** [comment]
Line numbers hit master in Emacs yesterday! Compiled Emacs directly from git and line numbers are working and looking good, and surprisingly so is everything else:

![line numbers](http://drop.bryan.sh/o8v63v2JlJ.png)

You'll also be happy to know that running Emacs from master dropped my startup time from 0.49s to 0.38s :)

**Comment by hlissner** [comment]
Fantastic! I'll add some conditionals to core-ui to prioritize this over nlinum.

Quick question: I'd like to update doom-themes and I know about `line-number-current-line`, but I couldn't find mention of a general face for line numbers. Is there one? Perhaps `line-number`?

> from 0.49s to 0.38s :)

![Muy bueno!](http://i0.kym-cdn.com/entries/icons/original/000/009/333/bueno.jpg)

**Comment by gilbertw1** [comment]
Yep, it's just `line-number`: http://git.savannah.gnu.org/cgit/emacs.git/tree/etc/NEWS#n440

Hahah, I was very pleased to see the speed increase!
