### ISSUE TITLE
Does magit really work?

### ISSUE THREAD

**Issue by saulius** [hlissner/.emacs.d#6]
After [magit was fixed](https://github.com/hlissner/.emacs.d/issues/4) I can now open it ant partially use [`evil-magit`](https://github.com/justbur/evil-magit) bindings. `s` -> `stage`, `u` -> `unstage` seem to work, but not the other. When I press `c` (`commit`) it says `Buffer is read-only: ...magit buffer name...`. Any advice?

**Comment by hlissner** [comment]
I haven't used magit lately (still trying to ween myself off git on the command line), so these bugs went unnoticed. I've removed some obsolete code that tried to get Magit to behave with my popup management system.

It _appears_ to work correctly now, but I'm new to `evil-magit`s bindings so I can't say how deep the problem goes. Please give it a try and let me know if you have any trouble with it!

**Comment by saulius** [comment]
Thanks again for your quick response @hlissner! Works like a charm :) magit is awesome - give it a try!
