### ISSUE TITLE
Receiving dependency errors updating packages

### ISSUE THREAD

**Issue by gilbertw1** [hlissner/.emacs.d#60]
Hi,

I've been getting the following error attempting to update packages (I've seen it with both ```rust-mode``` and ```all-the-icons```). My assumption is that it's happening when attempting to update any package the is a dependency of another package.

Error:

![Error](http://drop.bryan.codes/Jims5U1HhD.png)

I was able to resolve the issue by reverting this commit: https://github.com/hlissner/.emacs.d/commit/7d7ade82b316c08dccbd149b351419cc64903b8d

Thanks!

**Comment by hlissner** [comment]
You're right. I was aware of the problem, but I pushed a fix to it in https://github.com/hlissner/.emacs.d/commit/7f6c38fcb664b8252453ac02ea99f7064ab36fc0 (a very short while ago, so you likely missed the update).

**Comment by gilbertw1** [comment]
awesome, thanks! 👍
