### ISSUE TITLE
Wrong type argument: arryp, nil

### ISSUE THREAD

**Issue by galbacarys** [hlissner/.emacs.d#64]
Running on latest OS X 10.12, Emacs-plus installed through homebrew, 25.1.1. Using standard init.el.

When I run the make install script, I get the following output:
```
[...snip...]
Installed company-inf-ruby (ELPA)
Installed yard-mode (ELPA)
Installed ruby-refactor (ELPA)
Installed rspec-mode (ELPA)
Skipped inf-ruby (already installed)
Installed company-restclient (ELPA)
Skipped restclient (already installed)
Installed company-anaconda (ELPA)
Installed pip-requirements (ELPA)
Installed nose (ELPA)
Skipped anaconda-mode (already installed)
Installed phpunit (ELPA)
Installed php-refactor-mode (ELPA)
Installed php-mode (ELPA)
Wrong type argument: arrayp, nil
make: *** [install] Error 255
```

Any ideas on how to fix this one?

**Comment by hlissner** [comment]
Yikes. Could you try `DEBUG=1 make install`?

**Comment by galbacarys** [comment]
That's slightly more helpful! I don't know enough about emacs to fix it, but it looks reasonable-er.

```
Updating /Users/galbacarys/.emacs.d/.local/packages/quelpa/build/php-extras/
/Users/galbacarys/.emacs.d/.local/packages/quelpa/build/php-extras/php-extras-gen-eldoc.el -> /var/folders/xj/052fgc5n66j3k1w3d7_6hzbnp40m9s/T/php-extras58364cnf/php-extras-20160518.816/php-extras-gen-eldoc.el
/Users/galbacarys/.emacs.d/.local/packages/quelpa/build/php-extras/php-extras.el -> /var/folders/xj/052fgc5n66j3k1w3d7_6hzbnp40m9s/T/php-extras58364cnf/php-extras-20160518.816/php-extras.el
/Users/galbacarys/.emacs.d/.local/packages/quelpa/build/php-extras/dir -> /var/folders/xj/052fgc5n66j3k1w3d7_6hzbnp40m9s/T/php-extras58364cnf/php-extras-20160518.816/dir
Parsing tar file...
Parsing tar file...done
Error getting PACKAGE-DESC: (wrong-type-argument arrayp nil)
Wrong type argument: arrayp, nil
```

**Comment by hlissner** [comment]
Odd, that seems like a package.el issue, but I'm unable to reproduce it. I have a feeling that quelpa tried to install the package, failed halfway through and is using a corrupt repo in cache in future attempts to install the package.

Try deleting `~/.emacs.d/.local/packages/quelpa`, then try again. If it works, then I'll need to incorporate a little more errorhandling/cleanup for quelpa.

**Comment by keoko** [comment]
I had the same issue and I solve it installing gnu-tar package (see quelpa's documentation https://github.com/quelpa/quelpa#macos-instructions).
```
brew install gnu-tar
```

**Comment by hlissner** [comment]
@keoko Excellent, that's helpful to know. I just wrote [bin/doctor](https://github.com/hlissner/.emacs.d/blob/master/bin/doctor) (invoked via `make doctor`) as a tool to reveal environment problems and I've included a check for GNU tar.

@galbacarys Has your issue been resolved? If not, try pulling the latest and running `make doctor`. Perhaps it can she more light on the matter.

**Comment by hlissner** [comment]
@keoko Do you know if `tar-mode` is a recent addition to Emacs? Looking into it, package.el (and quelpa, by extension) do its tar-reading in-house (an implementation entirely in elisp). Meaning the system tar is never used.

From the [Emacs wiki](https://www.emacswiki.org/emacs/TarMode):

> Impressively, tar-mode doesn’t require the tar command, it directly manipulates the file.

**Comment by hlissner** [comment]
Nevermind, I was told on the Quelpa issue tracker that `package-build` uses the system tar. Looks like gnu vs bsd tar is definitely the issue!

**Comment by hlissner** [comment]
I'll consider this issue resolved for now. Feel free to reopen otherwise.
