### ISSUE TITLE
can't install doom in Mac OS

### ISSUE THREAD

**Issue by myimages** [hlissner/.emacs.d#71]
Hi ,

I cloned the repo as instructed by the readme file and when I run `make install` , I get this error
`Symbol's function definition is void: advice-add
make: *** [.local/autoloads.el] Error 255`

I am running GNU emacs 25.1.

**Comment by hlissner** [comment]
Try `emacs --version` in the command line. There's a high probability that the emacs being used is the one included with MacOS, which is version 22. 

The correct v25.1 binary is in /Applications/Emacs.app/Contents/MacOS/Emacs. This would quickly (albeit clumsily) fix it:

```bash
sudo rm -f /usr/bin/emacs
sudo ln -s /Applications/Emacs.app/Contents/MacOS/Emacs /usr/bin/emacs
```

A better solution, if you use [homebrew](https://brew.sh), would be:

```bash
brew install emacs --with-modules --with-imagemagick --with-cocoa
```

Make sure `/usr/local/bin` is in your `PATH`, and you're set.

**Comment by karetsu** [comment]
You can also do: `brew cask install emacs` to get a 'correct' version in place in /Applications.

Please do the second thing (installing homebrew - http://brew.sh - if necessary) and adjust your path by e.g. `echo PATH=/usr/local/bin:$PATH >> ~/.profile`

Works fine for me on macOS 10.12.whatever

**Comment by jmoore813** [comment]
I've reinstalled 25.2.1 (on macOS 10.12.4) and get the up to date version to load in both the GUI and terminal, but I am also receiving the same "Symbol's function definition is void: advice-add
make: *** [.local/autoloads.el] Error 255" error.  DEBUG=1 doesn't give me any other information

**Comment by hlissner** [comment]
I suspect it's the same problem. `advice-add` was added to Emacs in 24.4. Evidently the wrong version of Emacs is being launched from the makefile. Your PATH might be set up properly for the shell, but child processes can't see it. I assume you followed karetsu's advice:

`echo PATH=/usr/local/bin:$PATH >> ~/.profile`

If you have, then you need to export the variable too, run: `echo "export PATH" >> ~/.profile` 

That should fix the problem.

**Comment by myimages** [comment]
@hlissner  @karetsu thank you guys , it worked ! I am installing the packages right now.

@jmoore813 it worked for me , how did you install it ? make sure you follow one of the above instructions and you are all set.

**Comment by jmoore813** [comment]
@hlissner @karetsu @myimages Thanks all.  Restarting my shell wasn't doing it, I had to run `source ~/.profile` to get it to reload (which I really should have started out with).

**Comment by hlissner** [comment]
I'm glad it worked! 

A side note: if `~/.profile` isn't loading automatically for you (and you're using bash) put the contents of ~/.profile into `~/.bash_profile` instead. If you're using zsh, `~/.zshenv`.

I'll consider the issue resolved and close this.

**Comment by kou18n** [comment]
use this:
`sudo ln -s /Applications/Emacs.app/Contents/MacOS/Emacs /usr/local/bin/emacs`
