### ISSUE TITLE
Doesnt work with php

### ISSUE THREAD

**Issue by autoferrit** [hlissner/.emacs.d#81]
When opening up a php project and navigating to a file, it appears that there is no working php major mode. I am still fairly new to emacs. But when editing a php file, there is no syntax highlight and no completion. I have uncommented the `php` line in `init.el`.

I have also re-run the `install` and other setup commands as described in the readme setup and it just tells me theres no new files to compile. So im not sure what to try next.

**Comment by hlissner** [comment]
If you open the log (`M-x doom/popup-toggle-messages`), do you see any error messages after opening a php file?

**Comment by autoferrit** [comment]
Yes, I have these errors
![image](https://cloud.githubusercontent.com/assets/89895/26327016/8585b55c-3ef2-11e7-820e-fee334940c77.png)
I tried changing the font to fonts i have on the system, then running `make clean clean-cache && make all` but I still get the same error.

**Comment by hlissner** [comment]
I just pushed a fix. That should do it! Feel free to reopen if it didn't.

**Comment by autoferrit** [comment]
Ok that seems to work now. Thanks.

Do you know what plugin I could use, to add autocompletion to emacs for php so that it will properly complete class instances from other files? reading around there seems to be some long standing issues with `php-mode`. And havent been able to find many results yet on getting autocomplete to work intelligently.

**Comment by hlissner** [comment]
Unfortunately, the auto-completion situation for php isn't great. The best you can do at the moment is [company-php](https://github.com/xcwen/ac-php), which requires you to generate tags with [phpctags](https://github.com/xcwen/phpctags). This isn't automatic (you need to run `M-x ac-php-remake-tags`, and it's slow, but it's reasonably accurate.

I've been working on an ac-php+phpctags workflow for my config, but it still needs a lot of work.

**Comment by autoferrit** [comment]
that would be amazing. so far im liking emacs, and the autocompletion is one of the few things keeping me from using it for normal php development. I would be interested in your work.

I will try using the ctags setup. i have used it before but it has been a while and not with emacs.
