### ISSUE TITLE
projectile-recentf broken

### ISSUE THREAD

**Issue by gilbertw1** [hlissner/.emacs.d#86]
The ```projectile-recentf``` function is currently broken for doom. I tracked this down to the fact that all the filenames are formatted in abbreviated style (eg. '~/project/file.txt'), while projectile looks for the full project path in the recentf list to filter project specific recent files.

I've fixed the problem in my fork, by redefining the ```projectile-recentf-files``` to use the abbreviated project root:

https://github.com/gilbertw1/bmacs/commit/3a587fa7e63f6ba55e1ef4ac1321abed5b40faa0

I opted to keep the filename formatting, because I prefer the look of the abbreviated file names. 
I didn't create a pull request for this because I don't know how great of a solution it is :)

**Comment by hlissner** [comment]
I stumbled across this issue myself recently. Thanks for debugging it!

I opted to fix it with advice instead; it's a tad easier to debug should any issues arise from it later.

**Comment by gilbertw1** [comment]
Ah, abbreviate the project root via advice, much cleaner! I still have much to learn :)

**Comment by gilbertw1** [comment]
Hey, it looks like `projectile-recentf` is broken again after 9ed322ded60e2f015098c1c8b410493db7855987. It currently shows no files every time it's invoked.

I've verified this on my personal configuration and against the vanilla develop branch. Reverting the change fixes the problem. Thanks!

**Comment by hlissner** [comment]
What I used to do was I transformed all recentf entries with `abbreviate-file-name`, which was a bit hacky, and is was what prompted that projectile fix I removed in https://github.com/hlissner/doom-emacs/commit/9ed322ded60e2f015098c1c8b410493db7855987.

I undid this, and instead used an ivy transformer to abbreviate the file paths.

However, that means your old recentf file list is tainted. You can correct it by running:

```emacs-lisp
(setq recentf-list (mapcar #'expand-file-name recentf-list))
(recentf-save-list)
```

Alternatively, you can delete the file at `recentf-save-file` and start fresh.

**Comment by gilbertw1** [comment]
Hey, thanks for the quick response!

That makes total sense, however I'm running into an issue fixing this problem. If I run the command you provided, then `projectile-recentf` works correctly for the duration of the session. However, if I restart emacs `projectile-recentf` is empty again. Additionally, if I delete the cached `recentf` file, it still does not work properly, it only populates correctly if I run the snippet you provided above.

I've deleted the entire `.local` dir inside of a clean checkout of the develop branch and it produces the exact same behavior as mine. In the `recentf` cache file all the paths are absolute, I'm wondering if maybe they are being truncated when they're loaded?

Thanks!

**Comment by gilbertw1** [comment]
Hmmm.....looks like it's still modifying the `recent-list`:

https://github.com/hlissner/doom-emacs/blob/develop/core/core-editor.el#L158

Removing that line makes things work nicely.

**Comment by hlissner** [comment]
Ah! I was so certain I'd already deleted that line! My bad. Just got rid of it.

**Comment by gilbertw1** [comment]
Awesome! :+1:
