### ISSUE TITLE
evil-matchit not properly matching character pairs in visual mode

### ISSUE THREAD

**Issue by gilbertw1** [hlissner/.emacs.d#87]
Using the default configuration ```evil-matchit``` does not seem to be behaving properly in visual mode. Attempting to match parens (using ```%```) while in visual mode seems to simply jump the cursor (and selection) forward several characters (or does nothing if the delimiter appears at the end of the line).

Reproduce:

    (this is a test)
    ^ cursor here

After pressing v to enter visual mode and then % to run matchit:

    (this is a test)
       ^ cursor here

I would expect that the cursor would have moved to the matching parenthesis, which it correctly does when not in visual mode.

Thanks!

**Comment by hlissner** [comment]
Very strange. I'll look into this over the weekend!

**Comment by gilbertw1** [comment]
Thanks! I tested it out in Spacemacs and I'm seeing identical behavior, so I think it's probably an issue with evil-matchit. I'm not sure if maybe I don't understand the nuances of how it's supposed to work, but it appears to behave rather erratically, especially in visual mode.

**Comment by hlissner** [comment]
What major mode is this happening in?

**Comment by gilbertw1** [comment]
I've attempted (and succeeded) reproducing it in text-mode, java-mode, scala-mode, and lisp-mode. Here are two recorded examples, one in Scala, and one in Java.

Scala:
![scala](http://drop.bryan.codes/Oy9VpTU36R.gif)

Example Code:
```scala
object TestMatchit extends App {
  
  def foo(bar: Bar) {
    println("This is a foobar test")
  }
}
```

Java:
![java](http://drop.bryan.codes/nKOwqkiWaL.gif)

Example Code:
```java
class TestMatchit {
    public static void main(String[] args) {
        System.out.println("This is a test.")
    }
}
```

Each of those gifs, I'm essentially executing ```+evil/matchit``` in normal mode, and then afterwards in visual mode at the same spot. I haven't found a mode yet, where I haven't seen similar erratic behavior.

Thanks!

**Comment by hlissner** [comment]
Peculiar. I removed `+evil/matchit` from the equation and the problem disappeared. All it did was `(call-interactively #'evilmi-jump-items)`, so I'm not certain what caused that.

In any case, I made that command to silence evil-matchit's whining on some edge cases, which isn't very important, so I reverted it.

Give it a try and let me know if the problem persists.

Also, thank you for your comprehensive reports. It is an absolute delight working with you!

**Comment by gilbertw1** [comment]
Works much better! I thought I had tested it by binding ```evilmi-jump-items``` directly, but now I see it was probably still calling ```+evil/matchit``` due to it being remapped.

Thanks for the kind words...your one of the best project owners I've worked with and I'm glad that I can help improve this awesome software package in any way!
