### ISSUE TITLE
command-go-gocode-command is void

### ISSUE THREAD

**Issue by cosminilie** [hlissner/.emacs.d#89]
Hi,

There is a small problem in the go layer where 'command-go-gocode-command' is void since it's not set anywhere.
https://github.com/hlissner/.emacs.d/blob/157eb3e5dadb6678ad1d4ed64ef773c5aaab6027/modules/lang/go/config.el#L75

I fixed it in my config by adding  (setq command-go-gocode-command "gocode"). If you want a patch or want to fix it yourself let me know.

Best wishes,
Cosmin

**Comment by hlissner** [comment]
Thanks to @Luladjiev this should be fixed.
