### ISSUE TITLE
Makefile hostname & Emacs hotsname mismatch 

### ISSUE THREAD

**Issue by gcornut** [hlissner/.emacs.d#9]
I think this problem is rare, but on my machine, the host name obtained by the `hostname` command line is different from the host name obtained by the `(system-name)` emacs function. 

By default, the `hostname` command gives a short host name whereas the `(system-name)` function gives the full DNS host name (`<host>.<dns domain>`).

I've managed to fix this error simply by adding the `-f` argument for the `hostname` command in the  `CACHE_DIR` variable definition of the Makefile
```sh
CACHE_DIR="private/cache/`hostname -f`/"
```

**Comment by hlissner** [comment]
I decided to simply call `(system-name)` through Emacs from the makefile. That should reliably fix this issue. Thanks for reporting it!
