### ISSUE TITLE
Recursive load of saveplace

### ISSUE THREAD

**Issue by cthachuk** [hlissner/.emacs.d#94]
After updating to try the new private module implementation, I ran into a recursive load error when initializing.  This also occurs for me from a fresh install.  Log messages are below.  Git bisect points to commit 0150f78e87ca0a56473c36ab234ab9d23cd77c40, which defers the loading of saveplace (and others).  A simple revert of the commit runs into another error.  I'm happy to try any suggestions for a fix.

Thanks again.

Log after first bad commit:
```
Doom initialized
Loading package vi-tilde-fringe...
Configuring package vi-tilde-fringe...done (0.009s)
Loading package vi-tilde-fringe...done (0.028s)
Loading package shackle...
Configuring package shackle...done (0.010s)
Loading package shackle...done (0.047s)
Loading package smartparens...
file-symlink-p: Recursive load: "/usr/local/homebrew/Cellar/emacs-plus/25.2-rc2/share/emacs/25.2/lisp/saveplace.elc", "/usr/local/homebrew/Cellar/emacs-plus/25.2-rc2/share/emacs/25.2/lisp/saveplace.elc", "/usr/local/homebrew/Cellar/emacs-plus/25.2-rc2/share/emacs/25.2/lisp/saveplace.elc", "/usr/local/homebrew/Cellar/emacs-plus/25.2-rc2/share/emacs/25.2/lisp/saveplace.elc", "/usr/local/homebrew/Cellar/emacs-plus/25.2-rc2/share/emacs/25.2/lisp/saveplace.elc", "/Users/cthachuk/.emacs.d/.local/packages/elpa/smartparens-20170604.1126/smartparens.elc", "/Users/cthachuk/.emacs.d/core/core-editor.el", "/Users/cthachuk/.emacs.d/core/core.el", "/Users/cthachuk/.emacs.d/init.el"
```

Error in log after reverting bad commit: `Symbol's function definition is void: doom-themes-visual-bell-config`

**Comment by hlissner** [comment]
Sorry about that. I was a tad overzealous about deferring those packages, especially when the benefits were so meager. The issue should be fixed now. Feel free to reopen this if that isn't the case.
