### ISSUE TITLE
Recent Update Issues

### ISSUE THREAD

**Issue by gilbertw1** [hlissner/.emacs.d#95]
I'm currently working to track down more info on the following issues (which commit introduced them, etc.). I'm currently seeing a couple of issues after bringing my fork up to date:

**1.** Compiling & loading are failing due to ```doom-themes-visual-bell-config``` being a void function:

```
INIT-PACKAGES ERROR (/home/gilbertw1/.emacs.d/modules/ui/doom/config.el): (void-function doom-themes-visual-bell-config)
```

I'm guessing you have an update coming soon for doom-themes?

**2.** I am unable to run ```make compile``` on a clean checkout. I receive the following error when attempting to do so:

```
Format specifier doesn’t match argument type       
make: *** [Makefile:26: compile] Error 255
```

**3.** I've started receiving the following error on startup:

```
[persp-mode] Error: Can not autoresume perspectives -- (error Variable binding depth exceeds max-specpdl-size)
```

After which emacs become completely unresponsive to all further commands. Occasionally I'll see an additional error about ```lisp-eval-depth``` as well. I've tried updating the max values for both of these limits, but I've had no success so far.

I'll post more here, once I determine more about the causes of each error, and if modifications I've made are to blame.

Thanks!

**Comment by cthachuk** [comment]
Thanks @gilbertw1 for looking into this.  From a fresh install, I am experiencing the same error in 1.

**Comment by gilbertw1** [comment]
@cthachuk you should be able to work around 1 by commenting out that function call in ```modules/ui/doom/config.el``` (would give you a line number, but I'm mobile now)

**Comment by cthachuk** [comment]
Thanks, @gilbertw1.  Commenting indeed works around 1.  Just to confirm (sorry, no fix), I also quickly run into an error, related to 3, during interactive use (invoking a command for instance): `Lisp nesting exceeds 'max-lisp-eval-depth' `.

**Comment by hlissner** [comment]
Ack, sorry about that. I jumped the gun with a doom-themes update. I believe all three issues are related to that. I'm working on a fix now.

**Comment by hlissner** [comment]
I've zeroed in on the issue:

1 is caused by the `(doom-themes-visual-bell-config)` call on [line 40 in ui/doom/config.el](https://github.com/hlissner/.emacs.d/blob/master/modules/ui/doom/config.el#L40), which doesn't exist in doom-themes yet.

3 is caused by [line 247 in core/core-ui.el](https://github.com/hlissner/.emacs.d/blob/master/core/core-ui.el#L247). nlinum-hl-mode tries to activate nlinum-mode from nlinum-mode-hook, causing infinite recursion. I already fixed this in nlinum-hl, but published this update too soon, and it hasn't been pulled on Melpa yet.

2 I can't reproduce and am uncertain about, so far.

**Comment by gilbertw1** [comment]
Thanks for the quick response! I'm back up and running nicely after:

1. Commenting out the ```(doom-themes-visual-bell-config)``` call.
2. An additional run of ```make``` which updated ```nlinum-hl```

Regarding problem 2, it's a bit strange. I only noticed it when I tried to pull a clean copy of my config (and subsequently yours), and tried to run ```make compile``` for the first time on either. I can still compile properly on an existing config, but new ones fail everytime for me.

**Comment by hlissner** [comment]
You're right. I tried a fresh install and it would install the out-of-date nlinum-hl (with the recursion error). Very strange. I've bumped the version number. Perhaps it will fix itself in the next Melpa build.

**Comment by gilbertw1** [comment]
I found the source of problem 2:

```
Format specifier doesn’t match argument type       
make: *** [Makefile:26: compile] Error 255
```

The problem is that it's no longer using ```hlissner``` by default and that's the error it gets when there is no private module matching the user's username. You probably never see it since your computer obviously uses ```hlissner``` when you have a new checkout.

You might want to look into adding a friendly error message when this occurs and update your Readme to explain the need to copy the ```hlissner``` module or create a new one matching the user's username.

Looks like that explains all the issues I've run into. Thanks for your quick responses!

**Comment by hlissner** [comment]
That should do it, let me know if it continues.

**Comment by aminb** [comment]
I think that commit fixed that. Now the only issue is `(doom-themes-visual-bell-config)` not being available in `doom-themes` on `master`. I've commented that line out temporarily.

**Comment by hlissner** [comment]
Whoops! Forgot about that for a moment. 

I've commented it out for now, so you can safely update.

**Comment by aminb** [comment]
Thanks!

Also, just FYI, a `make install` on a fresh clone from latest `master` fails (probably due to 7005ae1 ?):

```elisp
Eager macro-expansion failure: (error "Package ‘persistent-soft-’ is unavailable")
Package ‘persistent-soft-’ is unavailable
make: *** [Makefile:51: .local/autoloads.el] Error 255
```

**Comment by hlissner** [comment]
@aminb I just pushed a update for that issue (in #96)

**Comment by aminb** [comment]
@hlissner Thanks, but I still got the same error on a fresh clone. Do you not get any errors on a new clone?
