### ISSUE TITLE
Insonsistent unicode font size in org-mode

### ISSUE THREAD

**Issue by tjikini** [hlissner/.emacs.d#97]
First off, thank you for great all-these-evil-things!

I am casual Emacs user, so I really dont sure where to put this issue.

With commented out [unicode font resetting](https://github.com/hlissner/.emacs.d/blob/master/modules/ui/doom/config.el#L24:L25) all looks fine (left **і's** is Cyrillic, right is Latin)

![26905706-7f9b2288-4bf1-11e7-9433-c9a898a04878](https://user-images.githubusercontent.com/22469167/26905908-a54de6a4-4bf2-11e7-8780-38e69c6fafd0.png)

But with [this](https://github.com/hlissner/.emacs.d/blob/master/modules/ui/doom/config.el#L24:L25) as is, even with identical fonts in `+doom-font` and `+doom-unicode-font`:

![26905706-7f9b2288-4bf1-11e7-9433-c9a898a04878](https://user-images.githubusercontent.com/22469167/26905937-c8908946-4bf2-11e7-9ac2-d52a2481d9dc.png)

With 
```
(defvar +doom-font
  (font-spec :family "Fira Mono" :size 13)
  "The font currently in use.")
...
(defvar +doom-unicode-font
  (font-spec :family "Fira Mono" :size 16)
  "Fallback font for unicode glyphs.")
```

![26905706-7f9b2288-4bf1-11e7-9433-c9a898a04878](https://user-images.githubusercontent.com/22469167/26905953-ea450b8e-4bf2-11e7-9022-a20ae202e385.png)

# #

**Comment by hlissner** [comment]
I just added the :feature unicode module. Try enabling it, running `make install`, then let me know if that solves your problem (it will take a couple seconds on first run).

**Comment by tjikini** [comment]
Still the same :(

**Comment by hlissner** [comment]
Sorry, made a few changes: I moved it from :feature to :ui, and I configured ui/doom to ignore `+doom-unicode-font`. Could you update again and see if that fixed it?

**Comment by tjikini** [comment]
Yep, that works, thank you!

**Comment by hlissner** [comment]
Phew! Good to hear. No problem!
