### ISSUE TITLE
bidi-paragraph-direction in org-mode has no effect

### ISSUE THREAD

**Issue by usharf** [hlissner/.emacs.d#98]
org-mode does not seem to respond to value stored in `bidi-paragraph-direction`, which when `nil`, should allow text in active buffer to flow `left-to-right` or `right-to-left` automatically, based on "first strong directional character". 

I've tried both Hebrew and Arabic (C-x RET C-\ hebrew).

I've tried setting this variable manually and in a hook. 
I have this is in my `modules/private/[user]/config.el:

```emacs-lisp
(add-hook! org-mode
  (dolist (face '(org-block
                  org-block-begin-line
                  org-meta-line
                  org-table
                  org-column
                  org-column-title))
    (when (facep face)
      (set-face-attribute face nil :font "Monospace")))
  (buffer-face-mode)
  (setq line-spacing 3)
  (setq bidi-paragraph-direction 'nil))
```
org: version: 9.0.8-elpa @ /home/uri/.emacs.d/.local/packages/elpa/org-20170606
emacs: 25.1.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.11) of 2017-03-29, modified by Debian)

**Comment by hlissner** [comment]
I've set `bidi-display-reordering` to `nil` in `core/core-ui.el` line 6 for a tiny performance boost, since i don't need it. Try adding:

```emacs-lisp
(setq bidi-display-reordering t)
```

**Comment by usharf** [comment]
Oh, great. That's it. I was looking for a related setting that might have an impact...

Any idea what might cause the same effect in prompts? i.e. at a counsel-find-file prompt, file names typed in rtl language like hebrew should also be reversed, as is the case in vanila emacs (-Q).

**Comment by hlissner** [comment]
Oh, my bad. I just realized that `bidi-display-reordering` is buffer-local. You should be doing 

```emacs-lisp
(setq-default bidi-display-reordering t)
```

**Comment by usharf** [comment]
@hlissner thanks!
