### ISSUE TITLE
Handy little wrapper function for hideshow toggle (```hs-toggle-hiding```)

### ISSUE THREAD

**Issue by gilbertw1** [hlissner/.emacs.d#99]
Hey!

I don't't know if you'd be interested or not, but I wrote a very tiny (but also very handy) wrapper for ```hs-toggle-hiding``` that makes it much easier to use. My biggest gripe with hideshow is that you have to be inside the scope of something you want to fold in order to actually fold it. In my ideal workflow, I could easily fold a function by just being anywhere on the line it starts on and easily initiate a fold for that function. This wrapper achieves that.

I've uploaded two short clips of me doing roughly the same thing with both functions to illustrate the differences between the two. Notice primarily how the first video always folds the outer scope based on the location of the point:

```hs-toggle-hiding``` - [video](http://drop.bryan.codes/tQ998bRUl8.mp4)
```modified-toggle``` - [video](http://drop.bryan.codes/rKlQcGiVEb.mp4)

Modified toggle function:

```elisp
(defun modified-toggle ()
  (interactive)
  (let ((saved-point (point)))
    (end-of-line)
    (hs-toggle-hiding)
    (goto-char saved-point)))
```

It plays very nicely in every scenario I've thrown at it. Anyways, feel free to close this issue, I just thought it was super handy and thought you might find it useful as well. 

I know that in many scenarios your workflow is different than mine, so if I'm sending too many of these random issues please let me know :)

**Comment by hlissner** [comment]
That's a good idea. This behavior makes much more sense. I've pushed it in https://github.com/hlissner/.emacs.d/commit/77eb06727c21c8e9c39cf59b2b50f75b4579b9ca.

Thanks again!

> if I'm sending too many of these random issues please let me know :)

Not at all. I look forward to them! You've inspired more than a few changes around here and given me plenty to think about.

**Comment by gilbertw1** [comment]
Awesome, I'll keep em coming :)
